-- Gastronomy suppliers, purchase orders and transactional stock receipts.

WITH permission_definitions(name, description) AS (
  VALUES
    ('gastronomy.suppliers.read', 'View gastronomy suppliers'),
    ('gastronomy.suppliers.write', 'Create and update gastronomy suppliers'),
    ('gastronomy.purchases.read', 'View gastronomy purchase orders and receipts'),
    ('gastronomy.purchases.write', 'Create and update gastronomy purchase orders'),
    ('gastronomy.purchases.receive', 'Receive gastronomy purchases into inventory')
)
INSERT INTO public.permissions(module_id, name, description)
SELECT m.id, d.name, d.description
FROM permission_definitions d
JOIN public.modules m ON m.code = 'gastronomy_tables'
ON CONFLICT (name) DO UPDATE SET description = EXCLUDED.description;

CREATE TABLE IF NOT EXISTS public.gastronomy_suppliers (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID REFERENCES public.companies(id) ON DELETE CASCADE NOT NULL,
  name VARCHAR(255) NOT NULL,
  tax_id VARCHAR(20),
  phone VARCHAR(50),
  email VARCHAR(255),
  address TEXT,
  active BOOLEAN DEFAULT true NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(company_id, name)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_gastronomy_suppliers_tax_id
  ON public.gastronomy_suppliers(company_id, tax_id)
  WHERE tax_id IS NOT NULL AND tax_id <> '';

CREATE TABLE IF NOT EXISTS public.gastronomy_purchase_orders (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID REFERENCES public.companies(id) ON DELETE CASCADE NOT NULL,
  branch_id UUID REFERENCES public.branches(id) ON DELETE RESTRICT NOT NULL,
  supplier_id UUID REFERENCES public.gastronomy_suppliers(id) ON DELETE RESTRICT NOT NULL,
  user_id UUID NOT NULL,
  order_number BIGINT GENERATED BY DEFAULT AS IDENTITY,
  status VARCHAR(30) DEFAULT 'draft' NOT NULL
    CHECK (status IN ('draft', 'ordered', 'partially_received', 'received', 'cancelled')),
  expected_at DATE,
  notes TEXT,
  total_estimated NUMERIC(14, 2) DEFAULT 0 NOT NULL CHECK (total_estimated >= 0),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  ordered_at TIMESTAMP WITH TIME ZONE,
  received_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS public.gastronomy_purchase_order_lines (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID REFERENCES public.companies(id) ON DELETE CASCADE NOT NULL,
  order_id UUID REFERENCES public.gastronomy_purchase_orders(id) ON DELETE CASCADE NOT NULL,
  ingredient_id UUID REFERENCES public.gastronomy_ingredients(id) ON DELETE RESTRICT NOT NULL,
  quantity_ordered NUMERIC(14, 3) NOT NULL CHECK (quantity_ordered > 0),
  quantity_received NUMERIC(14, 3) DEFAULT 0 NOT NULL
    CHECK (quantity_received >= 0 AND quantity_received <= quantity_ordered),
  unit_cost NUMERIC(14, 4) NOT NULL CHECK (unit_cost >= 0),
  UNIQUE(order_id, ingredient_id)
);

CREATE TABLE IF NOT EXISTS public.gastronomy_purchase_receipts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID REFERENCES public.companies(id) ON DELETE CASCADE NOT NULL,
  branch_id UUID REFERENCES public.branches(id) ON DELETE RESTRICT NOT NULL,
  order_id UUID REFERENCES public.gastronomy_purchase_orders(id) ON DELETE RESTRICT NOT NULL,
  user_id UUID NOT NULL,
  receipt_number BIGINT GENERATED BY DEFAULT AS IDENTITY,
  notes TEXT,
  received_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.gastronomy_purchase_receipt_lines (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID REFERENCES public.companies(id) ON DELETE CASCADE NOT NULL,
  receipt_id UUID REFERENCES public.gastronomy_purchase_receipts(id) ON DELETE CASCADE NOT NULL,
  order_line_id UUID REFERENCES public.gastronomy_purchase_order_lines(id) ON DELETE RESTRICT NOT NULL,
  ingredient_id UUID REFERENCES public.gastronomy_ingredients(id) ON DELETE RESTRICT NOT NULL,
  quantity NUMERIC(14, 3) NOT NULL CHECK (quantity > 0),
  unit_cost NUMERIC(14, 4) NOT NULL CHECK (unit_cost >= 0)
);

CREATE INDEX IF NOT EXISTS idx_gastronomy_suppliers_company
  ON public.gastronomy_suppliers(company_id, active, name);
CREATE INDEX IF NOT EXISTS idx_gastronomy_purchase_orders_branch
  ON public.gastronomy_purchase_orders(company_id, branch_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_gastronomy_purchase_lines_order
  ON public.gastronomy_purchase_order_lines(company_id, order_id);
CREATE INDEX IF NOT EXISTS idx_gastronomy_purchase_receipts_order
  ON public.gastronomy_purchase_receipts(company_id, branch_id, order_id, received_at DESC);
CREATE INDEX IF NOT EXISTS idx_gastronomy_purchase_receipt_lines_receipt
  ON public.gastronomy_purchase_receipt_lines(company_id, receipt_id);

ALTER TABLE public.gastronomy_suppliers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gastronomy_purchase_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gastronomy_purchase_order_lines ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gastronomy_purchase_receipts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gastronomy_purchase_receipt_lines ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Gastronomy suppliers by company" ON public.gastronomy_suppliers FOR ALL
  USING (company_id = public.jwt_company_id() AND public.jwt_business_type() = 'gastronomy')
  WITH CHECK (company_id = public.jwt_company_id() AND public.jwt_business_type() = 'gastronomy');
CREATE POLICY "Gastronomy purchase orders by company" ON public.gastronomy_purchase_orders FOR ALL
  USING (company_id = public.jwt_company_id() AND public.jwt_business_type() = 'gastronomy')
  WITH CHECK (company_id = public.jwt_company_id() AND public.jwt_business_type() = 'gastronomy');
CREATE POLICY "Gastronomy purchase order lines by company" ON public.gastronomy_purchase_order_lines FOR ALL
  USING (company_id = public.jwt_company_id() AND public.jwt_business_type() = 'gastronomy')
  WITH CHECK (company_id = public.jwt_company_id() AND public.jwt_business_type() = 'gastronomy');
CREATE POLICY "Gastronomy purchase receipts by company" ON public.gastronomy_purchase_receipts FOR ALL
  USING (company_id = public.jwt_company_id() AND public.jwt_business_type() = 'gastronomy')
  WITH CHECK (company_id = public.jwt_company_id() AND public.jwt_business_type() = 'gastronomy');
CREATE POLICY "Gastronomy purchase receipt lines by company" ON public.gastronomy_purchase_receipt_lines FOR ALL
  USING (company_id = public.jwt_company_id() AND public.jwt_business_type() = 'gastronomy')
  WITH CHECK (company_id = public.jwt_company_id() AND public.jwt_business_type() = 'gastronomy');

CREATE OR REPLACE FUNCTION public.gastronomy_list_suppliers(p_company_id UUID)
RETURNS TABLE(
  id UUID, name TEXT, tax_id TEXT, phone TEXT, email TEXT, address TEXT,
  active BOOLEAN, created_at TIMESTAMP WITH TIME ZONE
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT s.id, s.name::TEXT, COALESCE(s.tax_id, '')::TEXT, COALESCE(s.phone, '')::TEXT,
    COALESCE(s.email, '')::TEXT, COALESCE(s.address, '')::TEXT, s.active, s.created_at
  FROM public.gastronomy_suppliers s
  WHERE s.company_id = p_company_id
  ORDER BY s.active DESC, s.name;
$$;

CREATE OR REPLACE FUNCTION public.gastronomy_save_supplier(
  p_company_id UUID,
  p_supplier_id UUID,
  p_name TEXT,
  p_tax_id TEXT,
  p_phone TEXT,
  p_email TEXT,
  p_address TEXT,
  p_active BOOLEAN DEFAULT true
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_catalog
AS $$
DECLARE
  v_supplier_id UUID := p_supplier_id;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM public.companies c
    JOIN public.business_types bt ON bt.id = c.business_type_id
    WHERE c.id = p_company_id AND c.status = 'active' AND bt.code = 'gastronomy'
  ) THEN
    RAISE EXCEPTION 'INVALID_GASTRONOMY_COMPANY';
  END IF;

  IF v_supplier_id IS NULL THEN
    INSERT INTO public.gastronomy_suppliers(company_id, name, tax_id, phone, email, address, active)
    VALUES (p_company_id, p_name, NULLIF(p_tax_id, ''), NULLIF(p_phone, ''), NULLIF(p_email, ''), NULLIF(p_address, ''), p_active)
    RETURNING id INTO v_supplier_id;
  ELSE
    UPDATE public.gastronomy_suppliers SET
      name = p_name,
      tax_id = NULLIF(p_tax_id, ''),
      phone = NULLIF(p_phone, ''),
      email = NULLIF(p_email, ''),
      address = NULLIF(p_address, ''),
      active = p_active,
      updated_at = timezone('utc'::text, now())
    WHERE id = v_supplier_id AND company_id = p_company_id;
    IF NOT FOUND THEN RAISE EXCEPTION 'SUPPLIER_NOT_FOUND'; END IF;
  END IF;
  RETURN v_supplier_id;
EXCEPTION
  WHEN unique_violation THEN RAISE EXCEPTION 'SUPPLIER_ALREADY_EXISTS';
END;
$$;

CREATE OR REPLACE FUNCTION public.gastronomy_list_purchase_orders(p_company_id UUID, p_branch_id UUID)
RETURNS TABLE(
  id UUID, order_number BIGINT, supplier_id UUID, supplier_name TEXT, status TEXT,
  expected_at DATE, notes TEXT, total_estimated NUMERIC, created_at TIMESTAMP WITH TIME ZONE,
  ordered_at TIMESTAMP WITH TIME ZONE, received_at TIMESTAMP WITH TIME ZONE, lines JSONB
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT o.id, o.order_number, o.supplier_id, s.name::TEXT, o.status::TEXT, o.expected_at,
    COALESCE(o.notes, '')::TEXT, o.total_estimated, o.created_at, o.ordered_at, o.received_at,
    COALESCE(jsonb_agg(jsonb_build_object(
      'id', l.id,
      'ingredientId', l.ingredient_id,
      'ingredientName', i.name,
      'unit', i.unit,
      'quantityOrdered', l.quantity_ordered,
      'quantityReceived', l.quantity_received,
      'unitCost', l.unit_cost
    ) ORDER BY i.name) FILTER (WHERE l.id IS NOT NULL), '[]'::jsonb)
  FROM public.gastronomy_purchase_orders o
  JOIN public.gastronomy_suppliers s ON s.id = o.supplier_id AND s.company_id = o.company_id
  LEFT JOIN public.gastronomy_purchase_order_lines l ON l.order_id = o.id AND l.company_id = o.company_id
  LEFT JOIN public.gastronomy_ingredients i ON i.id = l.ingredient_id AND i.company_id = o.company_id
  WHERE o.company_id = p_company_id AND o.branch_id = p_branch_id
  GROUP BY o.id, s.name
  ORDER BY o.created_at DESC, o.order_number DESC;
$$;

CREATE OR REPLACE FUNCTION public.gastronomy_save_purchase_order(
  p_company_id UUID,
  p_branch_id UUID,
  p_user_id UUID,
  p_order_id UUID,
  p_supplier_id UUID,
  p_status TEXT,
  p_expected_at DATE,
  p_notes TEXT,
  p_lines JSONB
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_catalog
AS $$
DECLARE
  v_order_id UUID := p_order_id;
  v_total NUMERIC(14, 2);
BEGIN
  IF p_status NOT IN ('draft', 'ordered') OR jsonb_typeof(p_lines) <> 'array' OR jsonb_array_length(p_lines) = 0 THEN
    RAISE EXCEPTION 'INVALID_PURCHASE_ORDER';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM public.branches b WHERE b.id = p_branch_id AND b.company_id = p_company_id) THEN
    RAISE EXCEPTION 'BRANCH_COMPANY_MISMATCH';
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM public.gastronomy_suppliers s
    WHERE s.id = p_supplier_id AND s.company_id = p_company_id AND s.active
  ) THEN
    RAISE EXCEPTION 'SUPPLIER_NOT_FOUND';
  END IF;
  IF EXISTS (
    SELECT 1 FROM jsonb_array_elements(p_lines) line
    LEFT JOIN public.gastronomy_ingredients i
      ON i.id = (line->>'ingredientId')::UUID AND i.company_id = p_company_id AND i.active
    WHERE i.id IS NULL OR COALESCE((line->>'quantity')::NUMERIC, 0) <= 0
      OR COALESCE((line->>'unitCost')::NUMERIC, -1) < 0
  ) OR EXISTS (
    SELECT 1 FROM jsonb_array_elements(p_lines) line
    GROUP BY line->>'ingredientId' HAVING COUNT(*) > 1
  ) THEN
    RAISE EXCEPTION 'INVALID_PURCHASE_LINE';
  END IF;

  SELECT ROUND(SUM((line->>'quantity')::NUMERIC * (line->>'unitCost')::NUMERIC), 2)
  INTO v_total FROM jsonb_array_elements(p_lines) line;

  IF v_order_id IS NULL THEN
    INSERT INTO public.gastronomy_purchase_orders(
      company_id, branch_id, supplier_id, user_id, status, expected_at, notes,
      total_estimated, ordered_at
    ) VALUES (
      p_company_id, p_branch_id, p_supplier_id, p_user_id, p_status, p_expected_at,
      NULLIF(p_notes, ''), v_total,
      CASE WHEN p_status = 'ordered' THEN timezone('utc'::text, now()) ELSE NULL END
    ) RETURNING id INTO v_order_id;
  ELSE
    UPDATE public.gastronomy_purchase_orders SET
      supplier_id = p_supplier_id,
      status = p_status,
      expected_at = p_expected_at,
      notes = NULLIF(p_notes, ''),
      total_estimated = v_total,
      ordered_at = CASE WHEN p_status = 'ordered' THEN COALESCE(ordered_at, timezone('utc'::text, now())) ELSE NULL END,
      updated_at = timezone('utc'::text, now())
    WHERE id = v_order_id AND company_id = p_company_id AND branch_id = p_branch_id AND status IN ('draft', 'ordered');
    IF NOT FOUND THEN RAISE EXCEPTION 'PURCHASE_ORDER_NOT_EDITABLE'; END IF;
    DELETE FROM public.gastronomy_purchase_order_lines
    WHERE company_id = p_company_id AND order_id = v_order_id;
  END IF;

  INSERT INTO public.gastronomy_purchase_order_lines(
    company_id, order_id, ingredient_id, quantity_ordered, unit_cost
  )
  SELECT p_company_id, v_order_id, (line->>'ingredientId')::UUID,
    (line->>'quantity')::NUMERIC, (line->>'unitCost')::NUMERIC
  FROM jsonb_array_elements(p_lines) line;
  RETURN v_order_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.gastronomy_receive_purchase_order(
  p_company_id UUID,
  p_branch_id UUID,
  p_user_id UUID,
  p_order_id UUID,
  p_notes TEXT,
  p_lines JSONB
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_catalog
AS $$
DECLARE
  v_order public.gastronomy_purchase_orders%ROWTYPE;
  v_receipt_id UUID;
  v_receipt_number BIGINT;
  v_input RECORD;
  v_line public.gastronomy_purchase_order_lines%ROWTYPE;
  v_ingredient public.gastronomy_ingredients%ROWTYPE;
  v_status TEXT;
BEGIN
  IF jsonb_typeof(p_lines) <> 'array' OR jsonb_array_length(p_lines) = 0 THEN
    RAISE EXCEPTION 'INVALID_PURCHASE_RECEIPT';
  END IF;

  SELECT * INTO v_order FROM public.gastronomy_purchase_orders
  WHERE id = p_order_id AND company_id = p_company_id AND branch_id = p_branch_id
  FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'PURCHASE_ORDER_NOT_FOUND'; END IF;
  IF v_order.status NOT IN ('ordered', 'partially_received') THEN
    RAISE EXCEPTION 'PURCHASE_ORDER_NOT_RECEIVABLE';
  END IF;
  IF EXISTS (
    SELECT 1 FROM jsonb_array_elements(p_lines) line
    GROUP BY line->>'ingredientId' HAVING COUNT(*) > 1
  ) THEN
    RAISE EXCEPTION 'DUPLICATE_RECEIPT_INGREDIENT';
  END IF;

  -- Validate and lock every order line before changing stock.
  FOR v_input IN
    SELECT (line->>'ingredientId')::UUID AS ingredient_id,
      (line->>'quantity')::NUMERIC AS quantity,
      (line->>'unitCost')::NUMERIC AS unit_cost
    FROM jsonb_array_elements(p_lines) line
  LOOP
    IF v_input.quantity <= 0 OR v_input.unit_cost < 0 THEN RAISE EXCEPTION 'INVALID_RECEIPT_LINE'; END IF;
    SELECT * INTO v_line FROM public.gastronomy_purchase_order_lines
    WHERE company_id = p_company_id AND order_id = p_order_id AND ingredient_id = v_input.ingredient_id
    FOR UPDATE;
    IF NOT FOUND THEN RAISE EXCEPTION 'PURCHASE_LINE_NOT_FOUND'; END IF;
    IF v_line.quantity_received + v_input.quantity > v_line.quantity_ordered THEN
      RAISE EXCEPTION 'PURCHASE_OVER_RECEIPT';
    END IF;
    PERFORM 1 FROM public.gastronomy_ingredients
    WHERE id = v_input.ingredient_id AND company_id = p_company_id FOR UPDATE;
    IF NOT FOUND THEN RAISE EXCEPTION 'INGREDIENT_NOT_FOUND'; END IF;
  END LOOP;

  INSERT INTO public.gastronomy_purchase_receipts(company_id, branch_id, order_id, user_id, notes)
  VALUES (p_company_id, p_branch_id, p_order_id, p_user_id, NULLIF(p_notes, ''))
  RETURNING id, receipt_number INTO v_receipt_id, v_receipt_number;

  FOR v_input IN
    SELECT (line->>'ingredientId')::UUID AS ingredient_id,
      (line->>'quantity')::NUMERIC AS quantity,
      (line->>'unitCost')::NUMERIC AS unit_cost
    FROM jsonb_array_elements(p_lines) line
  LOOP
    SELECT * INTO v_line FROM public.gastronomy_purchase_order_lines
    WHERE company_id = p_company_id AND order_id = p_order_id AND ingredient_id = v_input.ingredient_id
    FOR UPDATE;
    SELECT * INTO v_ingredient FROM public.gastronomy_ingredients
    WHERE id = v_input.ingredient_id AND company_id = p_company_id FOR UPDATE;

    INSERT INTO public.gastronomy_purchase_receipt_lines(
      company_id, receipt_id, order_line_id, ingredient_id, quantity, unit_cost
    ) VALUES (
      p_company_id, v_receipt_id, v_line.id, v_input.ingredient_id, v_input.quantity, v_input.unit_cost
    );
    UPDATE public.gastronomy_purchase_order_lines SET
      quantity_received = quantity_received + v_input.quantity,
      unit_cost = v_input.unit_cost
    WHERE id = v_line.id;
    UPDATE public.gastronomy_ingredients SET
      cost_per_unit = CASE
        WHEN current_stock + v_input.quantity = 0 THEN v_input.unit_cost
        ELSE ROUND(((current_stock * cost_per_unit) + (v_input.quantity * v_input.unit_cost)) / (current_stock + v_input.quantity), 4)
      END,
      current_stock = current_stock + v_input.quantity,
      supplier_name = (SELECT s.name FROM public.gastronomy_suppliers s WHERE s.id = v_order.supplier_id),
      updated_at = timezone('utc'::text, now())
    WHERE id = v_input.ingredient_id AND company_id = p_company_id;
  END LOOP;

  SELECT CASE WHEN bool_and(quantity_received >= quantity_ordered) THEN 'received' ELSE 'partially_received' END
  INTO v_status FROM public.gastronomy_purchase_order_lines
  WHERE company_id = p_company_id AND order_id = p_order_id;
  UPDATE public.gastronomy_purchase_orders SET
    status = v_status,
    received_at = CASE WHEN v_status = 'received' THEN timezone('utc'::text, now()) ELSE NULL END,
    updated_at = timezone('utc'::text, now())
  WHERE id = p_order_id;

  RETURN jsonb_build_object(
    'receiptId', v_receipt_id,
    'receiptNumber', v_receipt_number,
    'orderId', p_order_id,
    'status', v_status
  );
END;
$$;

REVOKE ALL ON FUNCTION public.gastronomy_list_suppliers(UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.gastronomy_save_supplier(UUID, UUID, TEXT, TEXT, TEXT, TEXT, TEXT, BOOLEAN) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.gastronomy_list_purchase_orders(UUID, UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.gastronomy_save_purchase_order(UUID, UUID, UUID, UUID, UUID, TEXT, DATE, TEXT, JSONB) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.gastronomy_receive_purchase_order(UUID, UUID, UUID, UUID, TEXT, JSONB) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.gastronomy_list_suppliers(UUID) TO service_role;
GRANT EXECUTE ON FUNCTION public.gastronomy_save_supplier(UUID, UUID, TEXT, TEXT, TEXT, TEXT, TEXT, BOOLEAN) TO service_role;
GRANT EXECUTE ON FUNCTION public.gastronomy_list_purchase_orders(UUID, UUID) TO service_role;
GRANT EXECUTE ON FUNCTION public.gastronomy_save_purchase_order(UUID, UUID, UUID, UUID, UUID, TEXT, DATE, TEXT, JSONB) TO service_role;
GRANT EXECUTE ON FUNCTION public.gastronomy_receive_purchase_order(UUID, UUID, UUID, UUID, TEXT, JSONB) TO service_role;
