-- Partial purchase receipts, ASN reconciliation and EDI-ready receiving advice.

WITH permission_definitions(name, description) AS (
  VALUES
    ('supermarket.purchase_receipts.read', 'View partial supermarket purchase receipts'),
    ('supermarket.purchase_receipts.create', 'Create partial supermarket purchase receipts'),
    ('supermarket.edi.read', 'View queued supermarket EDI events')
)
INSERT INTO public.permissions(module_id, name, description)
SELECT m.id, d.name, d.description
FROM permission_definitions d
JOIN public.modules m ON m.code = 'barcode_scanner'
ON CONFLICT (name) DO UPDATE SET description = EXCLUDED.description;

ALTER TABLE public.supermarket_purchase_orders
  DROP CONSTRAINT IF EXISTS supermarket_purchase_orders_status_check;
ALTER TABLE public.supermarket_purchase_orders
  ADD CONSTRAINT supermarket_purchase_orders_status_check
  CHECK (status IN ('draft', 'ordered', 'partially_received', 'received', 'cancelled'));

CREATE TABLE IF NOT EXISTS public.supermarket_purchase_receipts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID REFERENCES public.companies(id) ON DELETE CASCADE NOT NULL,
  branch_id UUID REFERENCES public.branches(id) ON DELETE RESTRICT NOT NULL,
  order_id UUID REFERENCES public.supermarket_purchase_orders(id) ON DELETE CASCADE NOT NULL,
  shipment_id UUID REFERENCES public.supermarket_supplier_shipments(id) ON DELETE SET NULL,
  receipt_number BIGINT GENERATED BY DEFAULT AS IDENTITY,
  user_id UUID NOT NULL,
  idempotency_key VARCHAR(128) NOT NULL,
  received_on DATE DEFAULT CURRENT_DATE NOT NULL,
  delivery_note_number VARCHAR(80),
  accepted_quantity NUMERIC(14, 3) NOT NULL CHECK (accepted_quantity >= 0),
  rejected_quantity NUMERIC(14, 3) NOT NULL CHECK (rejected_quantity >= 0),
  remaining_quantity NUMERIC(14, 3) NOT NULL CHECK (remaining_quantity >= 0),
  reconciliation_status VARCHAR(30) NOT NULL
    CHECK (reconciliation_status IN ('matched', 'partial', 'rejected_items', 'document_mismatch', 'without_asn')),
  order_status VARCHAR(20) NOT NULL CHECK (order_status IN ('partially_received', 'received')),
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(company_id, receipt_number),
  UNIQUE(company_id, idempotency_key)
);

CREATE TABLE IF NOT EXISTS public.supermarket_purchase_receipt_lines (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID REFERENCES public.companies(id) ON DELETE CASCADE NOT NULL,
  receipt_id UUID REFERENCES public.supermarket_purchase_receipts(id) ON DELETE CASCADE NOT NULL,
  order_line_id UUID REFERENCES public.supermarket_purchase_order_lines(id) ON DELETE RESTRICT NOT NULL,
  product_id UUID REFERENCES public.products(id) ON DELETE RESTRICT NOT NULL,
  ordered_quantity NUMERIC(14, 3) NOT NULL CHECK (ordered_quantity > 0),
  previously_received NUMERIC(14, 3) NOT NULL CHECK (previously_received >= 0),
  accepted_quantity NUMERIC(14, 3) NOT NULL CHECK (accepted_quantity >= 0),
  rejected_quantity NUMERIC(14, 3) NOT NULL CHECK (rejected_quantity >= 0),
  remaining_quantity NUMERIC(14, 3) NOT NULL CHECK (remaining_quantity >= 0),
  unit_cost NUMERIC(14, 4) NOT NULL CHECK (unit_cost >= 0),
  lot_code VARCHAR(100),
  expiration_date DATE,
  UNIQUE(receipt_id, order_line_id)
);

CREATE TABLE IF NOT EXISTS public.supermarket_edi_outbox (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID REFERENCES public.companies(id) ON DELETE CASCADE NOT NULL,
  branch_id UUID REFERENCES public.branches(id) ON DELETE RESTRICT NOT NULL,
  event_type VARCHAR(10) NOT NULL CHECK (event_type IN ('DESADV', 'RECADV')),
  standard VARCHAR(20) DEFAULT 'EANCOM_D01B' NOT NULL,
  shipment_id UUID REFERENCES public.supermarket_supplier_shipments(id) ON DELETE CASCADE,
  receipt_id UUID REFERENCES public.supermarket_purchase_receipts(id) ON DELETE CASCADE,
  idempotency_key VARCHAR(180) NOT NULL,
  payload JSONB NOT NULL,
  status VARCHAR(20) DEFAULT 'pending' NOT NULL CHECK (status IN ('pending', 'processing', 'sent', 'failed')),
  retry_count INTEGER DEFAULT 0 NOT NULL CHECK (retry_count BETWEEN 0 AND 100),
  last_error TEXT,
  available_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  sent_at TIMESTAMP WITH TIME ZONE,
  UNIQUE(company_id, idempotency_key),
  CHECK ((shipment_id IS NOT NULL)::INTEGER + (receipt_id IS NOT NULL)::INTEGER = 1)
);

CREATE INDEX IF NOT EXISTS idx_supermarket_receipts_order
  ON public.supermarket_purchase_receipts(company_id, branch_id, order_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_supermarket_edi_pending
  ON public.supermarket_edi_outbox(status, available_at, created_at)
  WHERE status IN ('pending', 'failed');

ALTER TABLE public.supermarket_purchase_receipts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.supermarket_purchase_receipt_lines ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.supermarket_edi_outbox ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Supermarket purchase receipts by company" ON public.supermarket_purchase_receipts;
CREATE POLICY "Supermarket purchase receipts by company" ON public.supermarket_purchase_receipts FOR ALL
  USING (company_id = public.jwt_company_id() AND public.jwt_business_type() = 'supermarket')
  WITH CHECK (company_id = public.jwt_company_id() AND public.jwt_business_type() = 'supermarket');
DROP POLICY IF EXISTS "Supermarket purchase receipt lines by company" ON public.supermarket_purchase_receipt_lines;
CREATE POLICY "Supermarket purchase receipt lines by company" ON public.supermarket_purchase_receipt_lines FOR ALL
  USING (company_id = public.jwt_company_id() AND public.jwt_business_type() = 'supermarket')
  WITH CHECK (company_id = public.jwt_company_id() AND public.jwt_business_type() = 'supermarket');
DROP POLICY IF EXISTS "Supermarket EDI outbox by company" ON public.supermarket_edi_outbox;
CREATE POLICY "Supermarket EDI outbox by company" ON public.supermarket_edi_outbox FOR ALL
  USING (company_id = public.jwt_company_id() AND public.jwt_business_type() = 'supermarket')
  WITH CHECK (company_id = public.jwt_company_id() AND public.jwt_business_type() = 'supermarket');

CREATE OR REPLACE FUNCTION public.supermarket_queue_shipment_edi()
RETURNS TRIGGER
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_catalog
AS $$
BEGIN
  INSERT INTO public.supermarket_edi_outbox(
    company_id, branch_id, event_type, shipment_id, idempotency_key, payload
  ) VALUES (
    NEW.company_id, NEW.branch_id, 'DESADV', NEW.id,
    'DESADV:' || NEW.id::TEXT || ':' || floor(extract(epoch FROM NEW.updated_at) * 1000000)::BIGINT::TEXT,
    jsonb_build_object(
      'messageType', 'DESADV', 'shipmentId', NEW.id, 'orderId', NEW.order_id,
      'supplierId', NEW.supplier_id, 'dispatchNumber', NEW.dispatch_number,
      'carrier', NEW.carrier, 'trackingNumber', NEW.tracking_number,
      'shippedOn', NEW.shipped_on, 'estimatedArrival', NEW.estimated_arrival,
      'packageCount', NEW.package_count, 'palletCount', NEW.pallet_count,
      'status', NEW.status, 'generatedAt', timezone('utc'::text, now())
    )
  ) ON CONFLICT (company_id, idempotency_key) DO NOTHING;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS supermarket_supplier_shipment_edi ON public.supermarket_supplier_shipments;
CREATE TRIGGER supermarket_supplier_shipment_edi
  AFTER INSERT OR UPDATE ON public.supermarket_supplier_shipments
  FOR EACH ROW EXECUTE FUNCTION public.supermarket_queue_shipment_edi();

CREATE OR REPLACE FUNCTION public.supermarket_receive_purchase_partial(
  p_company_id UUID, p_branch_id UUID, p_user_id UUID, p_order_id UUID,
  p_idempotency_key TEXT, p_accepted_quantity NUMERIC, p_rejected_quantity NUMERIC,
  p_lot_code TEXT, p_expiration_date DATE, p_received_on DATE,
  p_delivery_note_number TEXT, p_notes TEXT
) RETURNS JSONB
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_catalog
AS $$
DECLARE
  v_order public.supermarket_purchase_orders%ROWTYPE;
  v_line public.supermarket_purchase_order_lines%ROWTYPE;
  v_existing public.supermarket_purchase_receipts%ROWTYPE;
  v_shipment public.supermarket_supplier_shipments%ROWTYPE;
  v_receipt_id UUID;
  v_receipt_number BIGINT;
  v_stock_id UUID;
  v_current_stock NUMERIC := 0;
  v_current_cost NUMERIC := 0;
  v_previously_received NUMERIC := 0;
  v_remaining_before NUMERIC;
  v_remaining_after NUMERIC;
  v_status TEXT;
  v_reconciliation TEXT;
  v_lot_code TEXT;
BEGIN
  PERFORM public.supermarket_assert_scope(p_company_id, p_branch_id);
  IF p_idempotency_key IS NULL OR length(p_idempotency_key) < 8 OR length(p_idempotency_key) > 128 THEN
    RAISE EXCEPTION 'INVALID_IDEMPOTENCY_KEY';
  END IF;
  PERFORM pg_advisory_xact_lock(hashtext(p_company_id::TEXT || ':' || p_idempotency_key));
  SELECT * INTO v_existing FROM public.supermarket_purchase_receipts
  WHERE company_id = p_company_id AND idempotency_key = p_idempotency_key;
  IF FOUND THEN
    RETURN jsonb_build_object('receiptId', v_existing.id, 'receiptNumber', v_existing.receipt_number,
      'orderStatus', v_existing.order_status, 'acceptedQuantity', v_existing.accepted_quantity,
      'rejectedQuantity', v_existing.rejected_quantity, 'remainingQuantity', v_existing.remaining_quantity,
      'reconciliationStatus', v_existing.reconciliation_status, 'duplicate', true);
  END IF;

  SELECT * INTO v_order FROM public.supermarket_purchase_orders
  WHERE id = p_order_id AND company_id = p_company_id AND branch_id = p_branch_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'PURCHASE_NOT_FOUND'; END IF;
  IF v_order.status NOT IN ('ordered', 'partially_received') THEN
    RAISE EXCEPTION 'PURCHASE_NOT_RECEIVABLE';
  END IF;
  SELECT * INTO v_line FROM public.supermarket_purchase_order_lines
  WHERE order_id = v_order.id AND company_id = p_company_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'PURCHASE_LINE_NOT_FOUND'; END IF;

  SELECT COALESCE(sum(rl.accepted_quantity), 0) INTO v_previously_received
  FROM public.supermarket_purchase_receipt_lines rl
  JOIN public.supermarket_purchase_receipts r ON r.id = rl.receipt_id AND r.company_id = rl.company_id
  WHERE r.company_id = p_company_id AND r.order_id = p_order_id;
  v_remaining_before := GREATEST(v_line.quantity - v_previously_received, 0);
  IF p_accepted_quantity < 0 OR p_rejected_quantity < 0
    OR p_accepted_quantity + p_rejected_quantity <= 0
    OR p_accepted_quantity + p_rejected_quantity > v_remaining_before
    OR p_received_on IS NULL OR p_received_on < CURRENT_DATE - 30 OR p_received_on > CURRENT_DATE + 1
    OR (p_expiration_date IS NOT NULL AND p_expiration_date < p_received_on)
    OR length(COALESCE(trim(p_delivery_note_number), '')) > 80
    OR length(COALESCE(trim(p_lot_code), '')) > 100 THEN
    RAISE EXCEPTION 'INVALID_PURCHASE_RECEIPT';
  END IF;
  v_remaining_after := GREATEST(v_remaining_before - p_accepted_quantity, 0);
  v_status := CASE WHEN v_remaining_after = 0 THEN 'received' ELSE 'partially_received' END;

  SELECT * INTO v_shipment FROM public.supermarket_supplier_shipments
  WHERE company_id = p_company_id AND branch_id = p_branch_id AND order_id = p_order_id;
  v_reconciliation := CASE
    WHEN v_shipment.id IS NULL THEN 'without_asn'
    WHEN NULLIF(trim(p_delivery_note_number), '') IS DISTINCT FROM v_shipment.dispatch_number THEN 'document_mismatch'
    WHEN p_rejected_quantity > 0 THEN 'rejected_items'
    WHEN p_accepted_quantity < v_remaining_before THEN 'partial'
    ELSE 'matched'
  END;

  INSERT INTO public.supermarket_purchase_receipts(
    company_id, branch_id, order_id, shipment_id, user_id, idempotency_key,
    received_on, delivery_note_number, accepted_quantity, rejected_quantity,
    remaining_quantity, reconciliation_status, order_status, notes
  ) VALUES (
    p_company_id, p_branch_id, p_order_id, v_shipment.id, p_user_id, p_idempotency_key,
    p_received_on, NULLIF(trim(p_delivery_note_number), ''), p_accepted_quantity,
    p_rejected_quantity, v_remaining_after, v_reconciliation, v_status, NULLIF(trim(p_notes), '')
  ) RETURNING id, receipt_number INTO v_receipt_id, v_receipt_number;

  v_lot_code := COALESCE(NULLIF(trim(p_lot_code), ''), NULLIF(trim(v_line.lot_code), ''),
    'OC-' || v_order.order_number::TEXT || '-R-' || v_receipt_number::TEXT);
  INSERT INTO public.supermarket_purchase_receipt_lines(
    company_id, receipt_id, order_line_id, product_id, ordered_quantity,
    previously_received, accepted_quantity, rejected_quantity, remaining_quantity,
    unit_cost, lot_code, expiration_date
  ) VALUES (
    p_company_id, v_receipt_id, v_line.id, v_line.product_id, v_line.quantity,
    v_previously_received, p_accepted_quantity, p_rejected_quantity, v_remaining_after,
    v_line.unit_cost, CASE WHEN p_accepted_quantity > 0 THEN v_lot_code ELSE NULL END,
    CASE WHEN p_accepted_quantity > 0 THEN p_expiration_date ELSE NULL END
  );

  IF p_accepted_quantity > 0 THEN
    SELECT p.cost INTO v_current_cost FROM public.products p
    WHERE p.id = v_line.product_id AND p.company_id = p_company_id FOR UPDATE;
    IF NOT FOUND THEN RAISE EXCEPTION 'PRODUCT_NOT_FOUND'; END IF;
    SELECT s.id, s.quantity INTO v_stock_id, v_current_stock FROM public.stock s
    WHERE s.company_id = p_company_id AND s.branch_id = p_branch_id AND s.product_id = v_line.product_id FOR UPDATE;
    v_current_stock := COALESCE(v_current_stock, 0);
    v_current_cost := COALESCE(v_current_cost, 0);
    IF v_stock_id IS NULL THEN
      INSERT INTO public.stock(company_id, branch_id, product_id, quantity, min_stock)
      VALUES (p_company_id, p_branch_id, v_line.product_id, p_accepted_quantity, 0)
      RETURNING id INTO v_stock_id;
    ELSE
      UPDATE public.stock SET quantity = quantity + p_accepted_quantity WHERE id = v_stock_id;
    END IF;
    UPDATE public.products SET cost = CASE WHEN v_current_stock + p_accepted_quantity = 0 THEN v_line.unit_cost
      ELSE ROUND(((v_current_stock * v_current_cost) + (p_accepted_quantity * v_line.unit_cost)) /
        (v_current_stock + p_accepted_quantity), 4) END,
      updated_at = timezone('utc'::text, now())
    WHERE id = v_line.product_id AND company_id = p_company_id;
    INSERT INTO public.stock_movements(company_id, stock_id, user_id, quantity, type, notes)
    VALUES (p_company_id, v_stock_id, p_user_id, p_accepted_quantity,
      'supermarket_purchase_receipt', 'Receipt ' || v_receipt_number || ' / Purchase ' || v_order.order_number);
    INSERT INTO public.supermarket_stock_lots(
      company_id, branch_id, product_id, purchase_order_line_id, lot_code,
      quantity_received, quantity_remaining, expiration_date, received_on
    ) VALUES (
      p_company_id, p_branch_id, v_line.product_id, v_line.id, v_lot_code,
      p_accepted_quantity, p_accepted_quantity, p_expiration_date, p_received_on
    ) ON CONFLICT (company_id, branch_id, product_id, lot_code) DO UPDATE SET
      quantity_received = public.supermarket_stock_lots.quantity_received + EXCLUDED.quantity_received,
      quantity_remaining = public.supermarket_stock_lots.quantity_remaining + EXCLUDED.quantity_remaining,
      expiration_date = COALESCE(EXCLUDED.expiration_date, public.supermarket_stock_lots.expiration_date);
  END IF;

  UPDATE public.supermarket_purchase_orders SET status = v_status,
    received_at = CASE WHEN v_status = 'received' THEN timezone('utc'::text, now()) ELSE NULL END,
    updated_at = timezone('utc'::text, now()) WHERE id = p_order_id;
  IF v_shipment.id IS NOT NULL THEN
    UPDATE public.supermarket_supplier_shipments SET
      status = CASE WHEN v_status = 'received' THEN 'delivered' ELSE 'in_transit' END,
      updated_at = timezone('utc'::text, now()) WHERE id = v_shipment.id;
  END IF;

  INSERT INTO public.supermarket_edi_outbox(
    company_id, branch_id, event_type, receipt_id, idempotency_key, payload
  ) VALUES (
    p_company_id, p_branch_id, 'RECADV', v_receipt_id, 'RECADV:' || v_receipt_id::TEXT,
    jsonb_build_object(
      'messageType', 'RECADV', 'receiptId', v_receipt_id, 'receiptNumber', v_receipt_number,
      'orderId', p_order_id, 'shipmentId', v_shipment.id, 'deliveryNoteNumber', NULLIF(trim(p_delivery_note_number), ''),
      'productId', v_line.product_id, 'orderedQuantity', v_line.quantity,
      'previouslyReceived', v_previously_received, 'acceptedQuantity', p_accepted_quantity,
      'rejectedQuantity', p_rejected_quantity, 'remainingQuantity', v_remaining_after,
      'reconciliationStatus', v_reconciliation, 'orderStatus', v_status,
      'receivedOn', p_received_on, 'generatedAt', timezone('utc'::text, now())
    )
  );

  RETURN jsonb_build_object('receiptId', v_receipt_id, 'receiptNumber', v_receipt_number,
    'orderStatus', v_status, 'acceptedQuantity', p_accepted_quantity,
    'rejectedQuantity', p_rejected_quantity, 'remainingQuantity', v_remaining_after,
    'reconciliationStatus', v_reconciliation, 'duplicate', false);
END;
$$;

CREATE OR REPLACE FUNCTION public.supermarket_list_purchase_receipts(
  p_company_id UUID, p_branch_id UUID, p_order_id UUID DEFAULT NULL
) RETURNS TABLE(
  id UUID, receipt_number BIGINT, order_id UUID, order_number BIGINT,
  supplier_name TEXT, product_id UUID, product_name TEXT, shipment_id UUID,
  delivery_note_number TEXT, received_on DATE, ordered_quantity NUMERIC,
  previously_received NUMERIC, accepted_quantity NUMERIC, rejected_quantity NUMERIC,
  remaining_quantity NUMERIC, lot_code TEXT, expiration_date DATE,
  reconciliation_status TEXT, order_status TEXT, notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE
)
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public, pg_catalog
AS $$
BEGIN
  PERFORM public.supermarket_assert_scope(p_company_id, p_branch_id);
  RETURN QUERY
  SELECT r.id, r.receipt_number, r.order_id, o.order_number, o.supplier_name::TEXT,
    rl.product_id, p.name::TEXT, r.shipment_id, COALESCE(r.delivery_note_number, '')::TEXT,
    r.received_on, rl.ordered_quantity, rl.previously_received, rl.accepted_quantity,
    rl.rejected_quantity, rl.remaining_quantity, COALESCE(rl.lot_code, '')::TEXT,
    rl.expiration_date, r.reconciliation_status::TEXT, r.order_status::TEXT,
    COALESCE(r.notes, '')::TEXT, r.created_at
  FROM public.supermarket_purchase_receipts r
  JOIN public.supermarket_purchase_receipt_lines rl ON rl.receipt_id = r.id AND rl.company_id = r.company_id
  JOIN public.supermarket_purchase_orders o ON o.id = r.order_id AND o.company_id = r.company_id
  JOIN public.products p ON p.id = rl.product_id AND p.company_id = rl.company_id
  WHERE r.company_id = p_company_id AND r.branch_id = p_branch_id
    AND (p_order_id IS NULL OR r.order_id = p_order_id)
  ORDER BY r.created_at DESC LIMIT 2000;
END;
$$;

DROP FUNCTION IF EXISTS public.supermarket_list_purchases(UUID, UUID);
CREATE FUNCTION public.supermarket_list_purchases(p_company_id UUID, p_branch_id UUID)
RETURNS TABLE(
  id UUID, supplier TEXT, product_id UUID, quantity NUMERIC, unit_cost NUMERIC,
  expected_date DATE, status TEXT, lot_code TEXT, expiration_date DATE,
  received_quantity NUMERIC, rejected_quantity NUMERIC, remaining_quantity NUMERIC,
  receipt_count BIGINT, shipment_id UUID, dispatch_number TEXT
)
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public, pg_catalog
AS $$
BEGIN
  PERFORM public.supermarket_assert_scope(p_company_id, p_branch_id);
  RETURN QUERY
  SELECT po.id, po.supplier_name::TEXT, pol.product_id, pol.quantity, pol.unit_cost,
    po.expected_on, po.status::TEXT, COALESCE(pol.lot_code, '')::TEXT, pol.expiration_date,
    CASE WHEN po.status = 'received' AND COALESCE(receipts.count, 0) = 0
      THEN pol.quantity ELSE COALESCE(receipts.accepted, 0) END,
    COALESCE(receipts.rejected, 0),
    CASE WHEN po.status = 'received' AND COALESCE(receipts.count, 0) = 0
      THEN 0 ELSE GREATEST(pol.quantity - COALESCE(receipts.accepted, 0), 0) END,
    COALESCE(receipts.count, 0),
    sh.id, COALESCE(sh.dispatch_number, '')::TEXT
  FROM public.supermarket_purchase_orders po
  JOIN public.supermarket_purchase_order_lines pol ON pol.order_id = po.id AND pol.company_id = po.company_id
  LEFT JOIN LATERAL (
    SELECT sum(rl.accepted_quantity) AS accepted, sum(rl.rejected_quantity) AS rejected, count(*) AS count
    FROM public.supermarket_purchase_receipts r
    JOIN public.supermarket_purchase_receipt_lines rl ON rl.receipt_id = r.id AND rl.company_id = r.company_id
    WHERE r.company_id = po.company_id AND r.order_id = po.id
  ) receipts ON true
  LEFT JOIN public.supermarket_supplier_shipments sh ON sh.company_id = po.company_id AND sh.order_id = po.id
  WHERE po.company_id = p_company_id AND po.branch_id = p_branch_id
  ORDER BY po.created_at DESC;
END;
$$;

CREATE OR REPLACE FUNCTION public.supermarket_receive_purchase(
  p_company_id UUID, p_branch_id UUID, p_user_id UUID, p_order_id UUID
) RETURNS UUID
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_catalog
AS $$
DECLARE v_line public.supermarket_purchase_order_lines%ROWTYPE; v_received NUMERIC; v_result JSONB;
BEGIN
  SELECT * INTO v_line FROM public.supermarket_purchase_order_lines
  WHERE company_id = p_company_id AND order_id = p_order_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'PURCHASE_LINE_NOT_FOUND'; END IF;
  SELECT COALESCE(sum(rl.accepted_quantity), 0) INTO v_received
  FROM public.supermarket_purchase_receipts r
  JOIN public.supermarket_purchase_receipt_lines rl ON rl.receipt_id = r.id AND rl.company_id = r.company_id
  WHERE r.company_id = p_company_id AND r.order_id = p_order_id;
  v_result := public.supermarket_receive_purchase_partial(
    p_company_id, p_branch_id, p_user_id, p_order_id,
    'legacy-receipt:' || p_order_id::TEXT, GREATEST(v_line.quantity - v_received, 0), 0,
    COALESCE(v_line.lot_code, ''), v_line.expiration_date, CURRENT_DATE, '', 'Legacy full receipt'
  );
  RETURN (v_result->>'receiptId')::UUID;
END;
$$;

-- Keep partially received orders visible to suppliers for subsequent deliveries.
CREATE OR REPLACE FUNCTION public.supermarket_supplier_portal_snapshot(p_token_hash TEXT)
RETURNS JSONB
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_catalog
AS $$
DECLARE v_access public.supermarket_supplier_portal_access%ROWTYPE; v_supplier public.supermarket_suppliers%ROWTYPE; v_orders JSONB;
BEGIN
  UPDATE public.supermarket_supplier_portal_access SET last_used_at = timezone('utc'::text, now())
  WHERE token_hash = lower(p_token_hash) AND active AND expires_at > timezone('utc'::text, now()) RETURNING * INTO v_access;
  IF NOT FOUND THEN RAISE EXCEPTION 'INVALID_SUPPLIER_PORTAL_TOKEN'; END IF;
  SELECT * INTO v_supplier FROM public.supermarket_suppliers
  WHERE id = v_access.supplier_id AND company_id = v_access.company_id AND active;
  IF NOT FOUND THEN RAISE EXCEPTION 'SUPPLIER_NOT_FOUND'; END IF;
  SELECT COALESCE(jsonb_agg(jsonb_build_object(
    'id', o.id, 'orderNumber', o.order_number, 'productName', p.name,
    'quantity', l.quantity, 'unitCost', l.unit_cost, 'total', ROUND(l.quantity * l.unit_cost, 2),
    'expectedDate', o.expected_on, 'status', o.status,
    'receivedQuantity', CASE WHEN o.status = 'received' AND COALESCE(receipts.count, 0) = 0
      THEN l.quantity ELSE COALESCE(receipts.accepted, 0) END,
    'remainingQuantity', CASE WHEN o.status = 'received' AND COALESCE(receipts.count, 0) = 0
      THEN 0 ELSE GREATEST(l.quantity - COALESCE(receipts.accepted, 0), 0) END,
    'deliveryStatus', c.status, 'promisedDate', c.promised_date, 'notes', COALESCE(c.notes, ''),
    'confirmedAt', c.confirmed_at, 'shipment', CASE WHEN sh.id IS NULL THEN NULL ELSE jsonb_build_object(
      'id', sh.id, 'dispatchNumber', sh.dispatch_number, 'carrier', sh.carrier,
      'trackingNumber', COALESCE(sh.tracking_number, ''), 'shippedOn', sh.shipped_on,
      'estimatedArrival', sh.estimated_arrival, 'packageCount', sh.package_count,
      'palletCount', sh.pallet_count, 'status', sh.status, 'notes', COALESCE(sh.notes, ''),
      'documentName', COALESCE(sh.document_name, ''), 'documentAvailable', sh.document_path IS NOT NULL
    ) END
  ) ORDER BY o.expected_on ASC NULLS LAST, o.order_number DESC), '[]'::JSONB) INTO v_orders
  FROM public.supermarket_purchase_orders o
  JOIN public.supermarket_purchase_order_lines l ON l.order_id = o.id AND l.company_id = o.company_id
  JOIN public.products p ON p.id = l.product_id AND p.company_id = l.company_id
  LEFT JOIN public.supermarket_supplier_delivery_confirmations c ON c.order_id = o.id AND c.company_id = o.company_id
  LEFT JOIN public.supermarket_supplier_shipments sh ON sh.order_id = o.id AND sh.company_id = o.company_id
  LEFT JOIN LATERAL (
    SELECT sum(rl.accepted_quantity) AS accepted, count(*) AS count
    FROM public.supermarket_purchase_receipts r
    JOIN public.supermarket_purchase_receipt_lines rl ON rl.receipt_id = r.id AND rl.company_id = r.company_id
    WHERE r.company_id = o.company_id AND r.order_id = o.id
  ) receipts ON true
  WHERE o.company_id = v_access.company_id AND o.branch_id = v_access.branch_id
    AND o.status IN ('ordered', 'partially_received', 'received')
    AND lower(trim(o.supplier_name)) = lower(trim(v_supplier.name));
  RETURN jsonb_build_object('supplier', jsonb_build_object('id', v_supplier.id, 'name', v_supplier.name,
    'email', COALESCE(v_supplier.email, ''), 'phone', COALESCE(v_supplier.phone, '')),
    'access', jsonb_build_object('label', v_access.label, 'expiresAt', v_access.expires_at), 'orders', v_orders);
END;
$$;

REVOKE ALL ON FUNCTION public.supermarket_receive_purchase_partial(UUID, UUID, UUID, UUID, TEXT, NUMERIC, NUMERIC, TEXT, DATE, DATE, TEXT, TEXT) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.supermarket_list_purchase_receipts(UUID, UUID, UUID) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.supermarket_list_purchases(UUID, UUID) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.supermarket_receive_purchase(UUID, UUID, UUID, UUID) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.supermarket_receive_purchase_partial(UUID, UUID, UUID, UUID, TEXT, NUMERIC, NUMERIC, TEXT, DATE, DATE, TEXT, TEXT) TO service_role;
GRANT EXECUTE ON FUNCTION public.supermarket_list_purchase_receipts(UUID, UUID, UUID) TO service_role;
GRANT EXECUTE ON FUNCTION public.supermarket_list_purchases(UUID, UUID) TO service_role;
GRANT EXECUTE ON FUNCTION public.supermarket_receive_purchase(UUID, UUID, UUID, UUID) TO service_role;
