-- Supermarket inventory controls: counts, waste, branch transfers and bulk pricing.

WITH permission_definitions(name, description) AS (
  VALUES
    ('supermarket.inventory.count', 'Register supermarket cycle counts'),
    ('supermarket.inventory.waste', 'Register supermarket waste'),
    ('supermarket.inventory.transfer', 'Transfer supermarket stock between branches'),
    ('supermarket.prices.bulk', 'Apply supermarket bulk price changes')
)
INSERT INTO public.permissions(module_id, name, description)
SELECT m.id, d.name, d.description
FROM permission_definitions d
JOIN public.modules m ON m.code = 'barcode_scanner'
ON CONFLICT (name) DO UPDATE SET description = EXCLUDED.description;

CREATE TABLE IF NOT EXISTS public.supermarket_inventory_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID REFERENCES public.companies(id) ON DELETE CASCADE NOT NULL,
  branch_id UUID REFERENCES public.branches(id) ON DELETE RESTRICT NOT NULL,
  product_id UUID REFERENCES public.products(id) ON DELETE RESTRICT NOT NULL,
  user_id UUID NOT NULL,
  idempotency_key VARCHAR(128) NOT NULL,
  operation VARCHAR(20) NOT NULL CHECK (operation IN ('count', 'waste')),
  previous_quantity NUMERIC(14, 3) NOT NULL CHECK (previous_quantity >= 0),
  declared_quantity NUMERIC(14, 3) NOT NULL CHECK (declared_quantity >= 0),
  delta NUMERIC(14, 3) NOT NULL,
  reason VARCHAR(160) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(company_id, idempotency_key)
);

CREATE TABLE IF NOT EXISTS public.supermarket_transfers (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID REFERENCES public.companies(id) ON DELETE CASCADE NOT NULL,
  source_branch_id UUID REFERENCES public.branches(id) ON DELETE RESTRICT NOT NULL,
  destination_branch_id UUID REFERENCES public.branches(id) ON DELETE RESTRICT NOT NULL,
  user_id UUID NOT NULL,
  transfer_number BIGINT GENERATED BY DEFAULT AS IDENTITY,
  idempotency_key VARCHAR(128) NOT NULL,
  status VARCHAR(20) DEFAULT 'completed' NOT NULL CHECK (status IN ('completed', 'cancelled')),
  notes VARCHAR(200),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  CHECK (source_branch_id <> destination_branch_id),
  UNIQUE(company_id, idempotency_key),
  UNIQUE(company_id, transfer_number)
);

CREATE TABLE IF NOT EXISTS public.supermarket_transfer_lines (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID REFERENCES public.companies(id) ON DELETE CASCADE NOT NULL,
  transfer_id UUID REFERENCES public.supermarket_transfers(id) ON DELETE CASCADE NOT NULL,
  product_id UUID REFERENCES public.products(id) ON DELETE RESTRICT NOT NULL,
  quantity NUMERIC(14, 3) NOT NULL CHECK (quantity > 0),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(transfer_id, product_id)
);

CREATE TABLE IF NOT EXISTS public.supermarket_price_batches (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID REFERENCES public.companies(id) ON DELETE CASCADE NOT NULL,
  user_id UUID NOT NULL,
  idempotency_key VARCHAR(128) NOT NULL,
  description VARCHAR(160) NOT NULL,
  updated_count INTEGER DEFAULT 0 NOT NULL CHECK (updated_count >= 0),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(company_id, idempotency_key)
);

CREATE TABLE IF NOT EXISTS public.supermarket_price_batch_lines (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID REFERENCES public.companies(id) ON DELETE CASCADE NOT NULL,
  batch_id UUID REFERENCES public.supermarket_price_batches(id) ON DELETE CASCADE NOT NULL,
  product_id UUID REFERENCES public.products(id) ON DELETE RESTRICT NOT NULL,
  previous_price NUMERIC(14, 2) NOT NULL CHECK (previous_price >= 0),
  new_price NUMERIC(14, 2) NOT NULL CHECK (new_price >= 0),
  previous_promo VARCHAR(20) NOT NULL,
  new_promo VARCHAR(20) NOT NULL,
  UNIQUE(batch_id, product_id)
);

CREATE INDEX IF NOT EXISTS idx_supermarket_inventory_events_branch
  ON public.supermarket_inventory_events(company_id, branch_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_supermarket_transfers_source
  ON public.supermarket_transfers(company_id, source_branch_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_supermarket_transfers_destination
  ON public.supermarket_transfers(company_id, destination_branch_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_supermarket_price_batches_company
  ON public.supermarket_price_batches(company_id, created_at DESC);

ALTER TABLE public.supermarket_inventory_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.supermarket_transfers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.supermarket_transfer_lines ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.supermarket_price_batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.supermarket_price_batch_lines ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Supermarket inventory events by company" ON public.supermarket_inventory_events FOR ALL
  USING (company_id = public.jwt_company_id() AND public.jwt_business_type() = 'supermarket')
  WITH CHECK (company_id = public.jwt_company_id() AND public.jwt_business_type() = 'supermarket');
CREATE POLICY "Supermarket transfers by company" ON public.supermarket_transfers FOR ALL
  USING (company_id = public.jwt_company_id() AND public.jwt_business_type() = 'supermarket')
  WITH CHECK (company_id = public.jwt_company_id() AND public.jwt_business_type() = 'supermarket');
CREATE POLICY "Supermarket transfer lines by company" ON public.supermarket_transfer_lines FOR ALL
  USING (company_id = public.jwt_company_id() AND public.jwt_business_type() = 'supermarket')
  WITH CHECK (company_id = public.jwt_company_id() AND public.jwt_business_type() = 'supermarket');
CREATE POLICY "Supermarket price batches by company" ON public.supermarket_price_batches FOR ALL
  USING (company_id = public.jwt_company_id() AND public.jwt_business_type() = 'supermarket')
  WITH CHECK (company_id = public.jwt_company_id() AND public.jwt_business_type() = 'supermarket');
CREATE POLICY "Supermarket price batch lines by company" ON public.supermarket_price_batch_lines FOR ALL
  USING (company_id = public.jwt_company_id() AND public.jwt_business_type() = 'supermarket')
  WITH CHECK (company_id = public.jwt_company_id() AND public.jwt_business_type() = 'supermarket');

CREATE OR REPLACE FUNCTION public.supermarket_list_branches(p_company_id UUID)
RETURNS TABLE(id UUID, name TEXT, is_main BOOLEAN, product_count BIGINT, stock_units NUMERIC)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, pg_catalog
AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM public.companies c JOIN public.business_types bt ON bt.id = c.business_type_id
    WHERE c.id = p_company_id AND c.status = 'active' AND bt.code = 'supermarket'
  ) THEN RAISE EXCEPTION 'INVALID_SUPERMARKET_COMPANY'; END IF;
  RETURN QUERY
  SELECT b.id, b.name::TEXT, b.is_main, COUNT(s.id), COALESCE(SUM(s.quantity), 0)
  FROM public.branches b
  LEFT JOIN public.stock s ON s.company_id = b.company_id AND s.branch_id = b.id
  WHERE b.company_id = p_company_id
  GROUP BY b.id
  ORDER BY b.is_main DESC, b.name;
END;
$$;

CREATE OR REPLACE FUNCTION public.supermarket_list_inventory_events(p_company_id UUID, p_branch_id UUID)
RETURNS TABLE(
  id UUID, product_id UUID, product_name TEXT, operation TEXT, previous_quantity NUMERIC,
  declared_quantity NUMERIC, delta NUMERIC, reason TEXT, created_at TIMESTAMP WITH TIME ZONE
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, pg_catalog
AS $$
BEGIN
  PERFORM public.supermarket_assert_scope(p_company_id, p_branch_id);
  RETURN QUERY
  SELECT e.id, e.product_id, p.name::TEXT, e.operation::TEXT, e.previous_quantity,
    e.declared_quantity, e.delta, e.reason::TEXT, e.created_at
  FROM public.supermarket_inventory_events e
  JOIN public.products p ON p.id = e.product_id AND p.company_id = e.company_id
  WHERE e.company_id = p_company_id AND e.branch_id = p_branch_id
  ORDER BY e.created_at DESC LIMIT 200;
END;
$$;

CREATE OR REPLACE FUNCTION public.supermarket_adjust_inventory(
  p_company_id UUID, p_branch_id UUID, p_user_id UUID, p_idempotency_key TEXT,
  p_product_id UUID, p_operation TEXT, p_quantity NUMERIC, p_reason TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_catalog
AS $$
DECLARE
  v_existing public.supermarket_inventory_events%ROWTYPE;
  v_stock public.stock%ROWTYPE;
  v_supermarket public.supermarket_products%ROWTYPE;
  v_lot public.supermarket_stock_lots%ROWTYPE;
  v_event_id UUID;
  v_delta NUMERIC(14, 3);
  v_remaining NUMERIC(14, 3);
  v_consumed NUMERIC(14, 3);
  v_adjustment_lot TEXT;
BEGIN
  PERFORM public.supermarket_assert_scope(p_company_id, p_branch_id);
  IF p_idempotency_key IS NULL OR length(p_idempotency_key) < 8 OR length(p_idempotency_key) > 128
    OR p_operation NOT IN ('count', 'waste') OR p_quantity < 0 OR trim(p_reason) = '' THEN
    RAISE EXCEPTION 'INVALID_INVENTORY_ADJUSTMENT';
  END IF;
  IF p_operation = 'waste' AND p_quantity <= 0 THEN RAISE EXCEPTION 'INVALID_INVENTORY_ADJUSTMENT'; END IF;
  PERFORM pg_advisory_xact_lock(hashtext(p_company_id::TEXT || ':' || p_idempotency_key));
  SELECT * INTO v_existing FROM public.supermarket_inventory_events
  WHERE company_id = p_company_id AND idempotency_key = p_idempotency_key;
  IF FOUND THEN
    RETURN jsonb_build_object('eventId', v_existing.id, 'operation', v_existing.operation,
      'previousQuantity', v_existing.previous_quantity, 'newQuantity', v_existing.previous_quantity + v_existing.delta,
      'delta', v_existing.delta, 'duplicate', true);
  END IF;
  SELECT * INTO v_supermarket FROM public.supermarket_products
  WHERE company_id = p_company_id AND product_id = p_product_id FOR UPDATE;
  SELECT * INTO v_stock FROM public.stock
  WHERE company_id = p_company_id AND branch_id = p_branch_id AND product_id = p_product_id FOR UPDATE;
  IF v_supermarket.product_id IS NULL OR v_stock.id IS NULL THEN RAISE EXCEPTION 'PRODUCT_NOT_FOUND'; END IF;
  IF NOT v_supermarket.is_weighed AND p_quantity <> TRUNC(p_quantity) THEN RAISE EXCEPTION 'INVALID_INVENTORY_ADJUSTMENT'; END IF;
  v_delta := CASE WHEN p_operation = 'count' THEN p_quantity - v_stock.quantity ELSE -p_quantity END;
  IF v_stock.quantity + v_delta < 0 THEN RAISE EXCEPTION 'INSUFFICIENT_STOCK'; END IF;

  UPDATE public.stock SET quantity = quantity + v_delta WHERE id = v_stock.id;
  INSERT INTO public.stock_movements(company_id, stock_id, user_id, quantity, type, notes)
  VALUES (p_company_id, v_stock.id, p_user_id, v_delta, 'supermarket_' || p_operation, trim(p_reason));

  IF v_delta < 0 THEN
    v_remaining := ABS(v_delta);
    FOR v_lot IN SELECT * FROM public.supermarket_stock_lots
      WHERE company_id = p_company_id AND branch_id = p_branch_id
        AND product_id = p_product_id AND quantity_remaining > 0
      ORDER BY expiration_date ASC NULLS LAST, received_on ASC, id ASC FOR UPDATE
    LOOP
      EXIT WHEN v_remaining <= 0;
      v_consumed := LEAST(v_lot.quantity_remaining, v_remaining);
      UPDATE public.supermarket_stock_lots SET quantity_remaining = quantity_remaining - v_consumed WHERE id = v_lot.id;
      v_remaining := v_remaining - v_consumed;
    END LOOP;
  ELSIF v_delta > 0 THEN
    v_adjustment_lot := 'COUNT-' || to_char(CURRENT_DATE, 'YYYYMMDD') || '-' || substr(gen_random_uuid()::TEXT, 1, 8);
    INSERT INTO public.supermarket_stock_lots(
      company_id, branch_id, product_id, lot_code, quantity_received, quantity_remaining, received_on
    ) VALUES (p_company_id, p_branch_id, p_product_id, v_adjustment_lot, v_delta, v_delta, CURRENT_DATE);
  END IF;

  INSERT INTO public.supermarket_inventory_events(
    company_id, branch_id, product_id, user_id, idempotency_key, operation,
    previous_quantity, declared_quantity, delta, reason
  ) VALUES (
    p_company_id, p_branch_id, p_product_id, p_user_id, p_idempotency_key, p_operation,
    v_stock.quantity, p_quantity, v_delta, trim(p_reason)
  ) RETURNING id INTO v_event_id;
  RETURN jsonb_build_object('eventId', v_event_id, 'operation', p_operation,
    'previousQuantity', v_stock.quantity, 'newQuantity', v_stock.quantity + v_delta,
    'delta', v_delta, 'duplicate', false);
END;
$$;

CREATE OR REPLACE FUNCTION public.supermarket_list_transfers(p_company_id UUID, p_branch_id UUID)
RETURNS TABLE(
  id UUID, transfer_number BIGINT, source_branch_id UUID, source_branch_name TEXT,
  destination_branch_id UUID, destination_branch_name TEXT, product_id UUID,
  product_name TEXT, quantity NUMERIC, status TEXT, notes TEXT, created_at TIMESTAMP WITH TIME ZONE
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, pg_catalog
AS $$
BEGIN
  PERFORM public.supermarket_assert_scope(p_company_id, p_branch_id);
  RETURN QUERY
  SELECT t.id, t.transfer_number, t.source_branch_id, sb.name::TEXT,
    t.destination_branch_id, db.name::TEXT, l.product_id, p.name::TEXT,
    l.quantity, t.status::TEXT, COALESCE(t.notes, '')::TEXT, t.created_at
  FROM public.supermarket_transfers t
  JOIN public.supermarket_transfer_lines l ON l.transfer_id = t.id AND l.company_id = t.company_id
  JOIN public.branches sb ON sb.id = t.source_branch_id AND sb.company_id = t.company_id
  JOIN public.branches db ON db.id = t.destination_branch_id AND db.company_id = t.company_id
  JOIN public.products p ON p.id = l.product_id AND p.company_id = t.company_id
  WHERE t.company_id = p_company_id AND (t.source_branch_id = p_branch_id OR t.destination_branch_id = p_branch_id)
  ORDER BY t.created_at DESC LIMIT 200;
END;
$$;

CREATE OR REPLACE FUNCTION public.supermarket_create_transfer(
  p_company_id UUID, p_source_branch_id UUID, p_destination_branch_id UUID,
  p_user_id UUID, p_idempotency_key TEXT, p_product_id UUID, p_quantity NUMERIC, p_notes TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_catalog
AS $$
DECLARE
  v_existing public.supermarket_transfers%ROWTYPE;
  v_source public.stock%ROWTYPE;
  v_destination public.stock%ROWTYPE;
  v_supermarket public.supermarket_products%ROWTYPE;
  v_lot public.supermarket_stock_lots%ROWTYPE;
  v_transfer_id UUID;
  v_transfer_number BIGINT;
  v_remaining NUMERIC(14, 3);
  v_consumed NUMERIC(14, 3);
BEGIN
  PERFORM public.supermarket_assert_scope(p_company_id, p_source_branch_id);
  PERFORM public.supermarket_assert_scope(p_company_id, p_destination_branch_id);
  IF p_source_branch_id = p_destination_branch_id OR p_quantity <= 0
    OR p_idempotency_key IS NULL OR length(p_idempotency_key) < 8 OR length(p_idempotency_key) > 128 THEN
    RAISE EXCEPTION 'INVALID_TRANSFER';
  END IF;
  PERFORM pg_advisory_xact_lock(hashtext(p_company_id::TEXT || ':' || p_idempotency_key));
  SELECT * INTO v_existing FROM public.supermarket_transfers
  WHERE company_id = p_company_id AND idempotency_key = p_idempotency_key;
  IF FOUND THEN
    RETURN jsonb_build_object('transferId', v_existing.id, 'transferNumber', v_existing.transfer_number, 'duplicate', true);
  END IF;
  SELECT * INTO v_supermarket FROM public.supermarket_products
  WHERE company_id = p_company_id AND product_id = p_product_id FOR UPDATE;
  SELECT * INTO v_source FROM public.stock
  WHERE company_id = p_company_id AND branch_id = p_source_branch_id AND product_id = p_product_id FOR UPDATE;
  IF v_supermarket.product_id IS NULL OR v_source.id IS NULL THEN RAISE EXCEPTION 'PRODUCT_NOT_FOUND'; END IF;
  IF NOT v_supermarket.is_weighed AND p_quantity <> TRUNC(p_quantity) THEN RAISE EXCEPTION 'INVALID_TRANSFER'; END IF;
  IF v_source.quantity < p_quantity THEN RAISE EXCEPTION 'INSUFFICIENT_STOCK'; END IF;
  SELECT * INTO v_destination FROM public.stock
  WHERE company_id = p_company_id AND branch_id = p_destination_branch_id AND product_id = p_product_id FOR UPDATE;
  IF v_destination.id IS NULL THEN
    INSERT INTO public.stock(company_id, branch_id, product_id, quantity, min_stock)
    VALUES (p_company_id, p_destination_branch_id, p_product_id, 0, v_source.min_stock)
    RETURNING * INTO v_destination;
  END IF;

  UPDATE public.stock SET quantity = quantity - p_quantity WHERE id = v_source.id;
  UPDATE public.stock SET quantity = quantity + p_quantity WHERE id = v_destination.id;
  INSERT INTO public.stock_movements(company_id, stock_id, user_id, quantity, type, notes)
  VALUES
    (p_company_id, v_source.id, p_user_id, -p_quantity, 'supermarket_transfer_out', COALESCE(NULLIF(trim(p_notes), ''), 'Transferencia entre sucursales')),
    (p_company_id, v_destination.id, p_user_id, p_quantity, 'supermarket_transfer_in', COALESCE(NULLIF(trim(p_notes), ''), 'Transferencia entre sucursales'));

  v_remaining := p_quantity;
  FOR v_lot IN SELECT * FROM public.supermarket_stock_lots
    WHERE company_id = p_company_id AND branch_id = p_source_branch_id
      AND product_id = p_product_id AND quantity_remaining > 0
    ORDER BY expiration_date ASC NULLS LAST, received_on ASC, id ASC FOR UPDATE
  LOOP
    EXIT WHEN v_remaining <= 0;
    v_consumed := LEAST(v_lot.quantity_remaining, v_remaining);
    UPDATE public.supermarket_stock_lots SET quantity_remaining = quantity_remaining - v_consumed WHERE id = v_lot.id;
    INSERT INTO public.supermarket_stock_lots(
      company_id, branch_id, product_id, lot_code, quantity_received,
      quantity_remaining, expiration_date, received_on
    ) VALUES (
      p_company_id, p_destination_branch_id, p_product_id, v_lot.lot_code,
      v_consumed, v_consumed, v_lot.expiration_date, CURRENT_DATE
    ) ON CONFLICT (company_id, branch_id, product_id, lot_code) DO UPDATE SET
      quantity_received = public.supermarket_stock_lots.quantity_received + EXCLUDED.quantity_received,
      quantity_remaining = public.supermarket_stock_lots.quantity_remaining + EXCLUDED.quantity_remaining;
    v_remaining := v_remaining - v_consumed;
  END LOOP;

  INSERT INTO public.supermarket_transfers(
    company_id, source_branch_id, destination_branch_id, user_id, idempotency_key, notes
  ) VALUES (
    p_company_id, p_source_branch_id, p_destination_branch_id, p_user_id,
    p_idempotency_key, NULLIF(trim(p_notes), '')
  ) RETURNING id, transfer_number INTO v_transfer_id, v_transfer_number;
  INSERT INTO public.supermarket_transfer_lines(company_id, transfer_id, product_id, quantity)
  VALUES (p_company_id, v_transfer_id, p_product_id, p_quantity);
  RETURN jsonb_build_object('transferId', v_transfer_id, 'transferNumber', v_transfer_number, 'duplicate', false);
END;
$$;

CREATE OR REPLACE FUNCTION public.supermarket_apply_bulk_prices(
  p_company_id UUID, p_user_id UUID, p_idempotency_key TEXT, p_description TEXT, p_items JSONB
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_catalog
AS $$
DECLARE
  v_existing public.supermarket_price_batches%ROWTYPE;
  v_product public.products%ROWTYPE;
  v_supermarket public.supermarket_products%ROWTYPE;
  v_item JSONB;
  v_product_id UUID;
  v_new_price NUMERIC(14, 2);
  v_new_promo TEXT;
  v_batch_id UUID;
  v_updated INTEGER := 0;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM public.companies c JOIN public.business_types bt ON bt.id = c.business_type_id
    WHERE c.id = p_company_id AND c.status = 'active' AND bt.code = 'supermarket'
  ) THEN RAISE EXCEPTION 'INVALID_SUPERMARKET_COMPANY'; END IF;
  IF p_idempotency_key IS NULL OR length(p_idempotency_key) < 8 OR length(p_idempotency_key) > 128
    OR trim(p_description) = '' OR jsonb_typeof(p_items) <> 'array'
    OR jsonb_array_length(p_items) < 1 OR jsonb_array_length(p_items) > 5000 THEN
    RAISE EXCEPTION 'INVALID_PRICE_BATCH';
  END IF;
  IF EXISTS (SELECT 1 FROM jsonb_array_elements(p_items) item GROUP BY item->>'productId' HAVING COUNT(*) > 1) THEN
    RAISE EXCEPTION 'DUPLICATE_PRICE_ITEM';
  END IF;
  PERFORM pg_advisory_xact_lock(hashtext(p_company_id::TEXT || ':' || p_idempotency_key));
  SELECT * INTO v_existing FROM public.supermarket_price_batches
  WHERE company_id = p_company_id AND idempotency_key = p_idempotency_key;
  IF FOUND THEN
    RETURN jsonb_build_object('batchId', v_existing.id, 'updatedCount', v_existing.updated_count, 'duplicate', true);
  END IF;
  INSERT INTO public.supermarket_price_batches(company_id, user_id, idempotency_key, description)
  VALUES (p_company_id, p_user_id, p_idempotency_key, trim(p_description)) RETURNING id INTO v_batch_id;
  FOR v_item IN SELECT value FROM jsonb_array_elements(p_items)
  LOOP
    BEGIN
      v_product_id := (v_item->>'productId')::UUID;
      v_new_price := (v_item->>'newPrice')::NUMERIC;
      v_new_promo := COALESCE(v_item->>'promo', 'none');
    EXCEPTION WHEN OTHERS THEN RAISE EXCEPTION 'INVALID_PRICE_ITEM'; END;
    IF v_new_price < 0 OR v_new_promo NOT IN ('none', '2x1', '30off') THEN RAISE EXCEPTION 'INVALID_PRICE_ITEM'; END IF;
    SELECT * INTO v_product FROM public.products WHERE company_id = p_company_id AND id = v_product_id FOR UPDATE;
    SELECT * INTO v_supermarket FROM public.supermarket_products WHERE company_id = p_company_id AND product_id = v_product_id FOR UPDATE;
    IF v_product.id IS NULL OR v_supermarket.product_id IS NULL THEN RAISE EXCEPTION 'PRODUCT_NOT_FOUND'; END IF;
    INSERT INTO public.supermarket_price_batch_lines(
      company_id, batch_id, product_id, previous_price, new_price, previous_promo, new_promo
    ) VALUES (
      p_company_id, v_batch_id, v_product_id, v_product.price, v_new_price, v_supermarket.promo, v_new_promo
    );
    UPDATE public.products SET price = v_new_price, updated_at = timezone('utc'::text, now())
    WHERE company_id = p_company_id AND id = v_product_id;
    UPDATE public.supermarket_products SET promo = v_new_promo, updated_at = timezone('utc'::text, now())
    WHERE company_id = p_company_id AND product_id = v_product_id;
    v_updated := v_updated + 1;
  END LOOP;
  UPDATE public.supermarket_price_batches SET updated_count = v_updated WHERE id = v_batch_id;
  RETURN jsonb_build_object('batchId', v_batch_id, 'updatedCount', v_updated, 'duplicate', false);
END;
$$;

REVOKE ALL ON FUNCTION public.supermarket_list_branches(UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.supermarket_list_inventory_events(UUID, UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.supermarket_adjust_inventory(UUID, UUID, UUID, TEXT, UUID, TEXT, NUMERIC, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.supermarket_list_transfers(UUID, UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.supermarket_create_transfer(UUID, UUID, UUID, UUID, TEXT, UUID, NUMERIC, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.supermarket_apply_bulk_prices(UUID, UUID, TEXT, TEXT, JSONB) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.supermarket_list_branches(UUID) TO service_role;
GRANT EXECUTE ON FUNCTION public.supermarket_list_inventory_events(UUID, UUID) TO service_role;
GRANT EXECUTE ON FUNCTION public.supermarket_adjust_inventory(UUID, UUID, UUID, TEXT, UUID, TEXT, NUMERIC, TEXT) TO service_role;
GRANT EXECUTE ON FUNCTION public.supermarket_list_transfers(UUID, UUID) TO service_role;
GRANT EXECUTE ON FUNCTION public.supermarket_create_transfer(UUID, UUID, UUID, UUID, TEXT, UUID, NUMERIC, TEXT) TO service_role;
GRANT EXECUTE ON FUNCTION public.supermarket_apply_bulk_prices(UUID, UUID, TEXT, TEXT, JSONB) TO service_role;
