-- Supplier discrepancy claims created from purchase receipts and exchanged through EDI COMDIS.

WITH permission_definitions(name, description) AS (
  VALUES
    ('supermarket.supplier_claims.read', 'View supermarket supplier discrepancy claims'),
    ('supermarket.supplier_claims.manage', 'Acknowledge and resolve supermarket supplier discrepancy claims')
)
INSERT INTO public.permissions(module_id, name, description)
SELECT m.id, d.name, d.description
FROM permission_definitions d
JOIN public.modules m ON m.code = 'barcode_scanner'
ON CONFLICT (name) DO UPDATE SET description = EXCLUDED.description;

CREATE TABLE IF NOT EXISTS public.supermarket_supplier_claims (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID REFERENCES public.companies(id) ON DELETE CASCADE NOT NULL,
  branch_id UUID REFERENCES public.branches(id) ON DELETE RESTRICT NOT NULL,
  supplier_id UUID REFERENCES public.supermarket_suppliers(id) ON DELETE SET NULL,
  supplier_name VARCHAR(255) NOT NULL,
  order_id UUID REFERENCES public.supermarket_purchase_orders(id) ON DELETE CASCADE NOT NULL,
  receipt_id UUID REFERENCES public.supermarket_purchase_receipts(id) ON DELETE CASCADE NOT NULL,
  product_id UUID REFERENCES public.products(id) ON DELETE RESTRICT NOT NULL,
  claim_number BIGINT GENERATED BY DEFAULT AS IDENTITY,
  claim_type VARCHAR(30) NOT NULL
    CHECK (claim_type IN ('partial_delivery', 'rejected_items', 'document_mismatch', 'missing_asn')),
  status VARCHAR(20) DEFAULT 'open' NOT NULL
    CHECK (status IN ('open', 'acknowledged', 'disputed', 'resolved')),
  priority VARCHAR(10) DEFAULT 'normal' NOT NULL CHECK (priority IN ('normal', 'urgent')),
  subject VARCHAR(180) NOT NULL,
  description TEXT NOT NULL,
  claimed_quantity NUMERIC(14, 3) NOT NULL CHECK (claimed_quantity >= 0),
  response_due_on DATE NOT NULL,
  resolution_notes TEXT,
  opened_by UUID NOT NULL,
  acknowledged_at TIMESTAMP WITH TIME ZONE,
  resolved_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(company_id, claim_number),
  UNIQUE(company_id, receipt_id)
);

CREATE TABLE IF NOT EXISTS public.supermarket_supplier_claim_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID REFERENCES public.companies(id) ON DELETE CASCADE NOT NULL,
  branch_id UUID REFERENCES public.branches(id) ON DELETE RESTRICT NOT NULL,
  claim_id UUID REFERENCES public.supermarket_supplier_claims(id) ON DELETE CASCADE NOT NULL,
  actor_type VARCHAR(20) NOT NULL CHECK (actor_type IN ('system', 'internal', 'supplier')),
  actor_id UUID,
  idempotency_key VARCHAR(128) NOT NULL,
  from_status VARCHAR(20),
  to_status VARCHAR(20) NOT NULL CHECK (to_status IN ('open', 'acknowledged', 'disputed', 'resolved')),
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(company_id, idempotency_key)
);

CREATE INDEX IF NOT EXISTS idx_supermarket_supplier_claims_queue
  ON public.supermarket_supplier_claims(company_id, branch_id, status, response_due_on, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_supermarket_supplier_claims_supplier
  ON public.supermarket_supplier_claims(company_id, supplier_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_supermarket_supplier_claim_events_history
  ON public.supermarket_supplier_claim_events(company_id, claim_id, created_at DESC);

ALTER TABLE public.supermarket_supplier_claims ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.supermarket_supplier_claim_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Supermarket supplier claims by company" ON public.supermarket_supplier_claims;
CREATE POLICY "Supermarket supplier claims by company" ON public.supermarket_supplier_claims FOR ALL
  USING (company_id = public.jwt_company_id() AND public.jwt_business_type() = 'supermarket')
  WITH CHECK (company_id = public.jwt_company_id() AND public.jwt_business_type() = 'supermarket');
DROP POLICY IF EXISTS "Supermarket supplier claim events by company" ON public.supermarket_supplier_claim_events;
CREATE POLICY "Supermarket supplier claim events by company" ON public.supermarket_supplier_claim_events FOR ALL
  USING (company_id = public.jwt_company_id() AND public.jwt_business_type() = 'supermarket')
  WITH CHECK (company_id = public.jwt_company_id() AND public.jwt_business_type() = 'supermarket');

ALTER TABLE public.supermarket_edi_outbox
  ADD COLUMN IF NOT EXISTS claim_id UUID REFERENCES public.supermarket_supplier_claims(id) ON DELETE CASCADE;
ALTER TABLE public.supermarket_edi_outbox
  DROP CONSTRAINT IF EXISTS supermarket_edi_outbox_event_type_check;
ALTER TABLE public.supermarket_edi_outbox
  ADD CONSTRAINT supermarket_edi_outbox_event_type_check CHECK (event_type IN ('DESADV', 'RECADV', 'COMDIS'));
ALTER TABLE public.supermarket_edi_outbox
  DROP CONSTRAINT IF EXISTS supermarket_edi_outbox_check;
ALTER TABLE public.supermarket_edi_outbox
  DROP CONSTRAINT IF EXISTS supermarket_edi_outbox_source_check;
ALTER TABLE public.supermarket_edi_outbox
  ADD CONSTRAINT supermarket_edi_outbox_source_check
  CHECK ((shipment_id IS NOT NULL)::INTEGER + (receipt_id IS NOT NULL)::INTEGER + (claim_id IS NOT NULL)::INTEGER = 1);

CREATE OR REPLACE FUNCTION public.supermarket_open_receipt_claim()
RETURNS TRIGGER
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_catalog
AS $$
DECLARE
  v_receipt public.supermarket_purchase_receipts%ROWTYPE;
  v_order public.supermarket_purchase_orders%ROWTYPE;
  v_line public.supermarket_purchase_receipt_lines%ROWTYPE;
  v_supplier_id UUID;
  v_claim_id UUID;
  v_type TEXT;
  v_priority TEXT;
  v_subject TEXT;
  v_claimed NUMERIC;
BEGIN
  SELECT * INTO v_receipt FROM public.supermarket_purchase_receipts
  WHERE id = NEW.receipt_id AND company_id = NEW.company_id;
  IF NOT FOUND OR v_receipt.reconciliation_status = 'matched' THEN RETURN NEW; END IF;
  SELECT * INTO v_order FROM public.supermarket_purchase_orders
  WHERE id = v_receipt.order_id AND company_id = NEW.company_id;
  SELECT * INTO v_line FROM public.supermarket_purchase_receipt_lines
  WHERE id = NEW.id AND receipt_id = NEW.receipt_id AND company_id = NEW.company_id;
  IF NOT FOUND THEN RETURN NEW; END IF;
  SELECT id INTO v_supplier_id FROM public.supermarket_suppliers
  WHERE company_id = NEW.company_id AND active
    AND lower(trim(name)) = lower(trim(v_order.supplier_name)) LIMIT 1;

  v_type := CASE
    WHEN v_receipt.reconciliation_status = 'document_mismatch' THEN 'document_mismatch'
    WHEN v_receipt.rejected_quantity > 0 THEN 'rejected_items'
    WHEN v_receipt.remaining_quantity > 0 THEN 'partial_delivery'
    ELSE 'missing_asn'
  END;
  v_priority := CASE WHEN v_type IN ('rejected_items', 'document_mismatch') THEN 'urgent' ELSE 'normal' END;
  v_claimed := CASE WHEN v_receipt.rejected_quantity > 0 THEN v_receipt.rejected_quantity
    WHEN v_receipt.remaining_quantity > 0 THEN v_receipt.remaining_quantity ELSE v_receipt.accepted_quantity END;
  v_subject := CASE v_type
    WHEN 'rejected_items' THEN 'Mercaderia rechazada en recepcion'
    WHEN 'partial_delivery' THEN 'Entrega parcial pendiente'
    WHEN 'document_mismatch' THEN 'Diferencia entre remito y ASN'
    ELSE 'Recepcion sin aviso de despacho' END;

  INSERT INTO public.supermarket_supplier_claims(
    company_id, branch_id, supplier_id, supplier_name, order_id, receipt_id, product_id,
    claim_type, priority, subject, description, claimed_quantity, response_due_on, opened_by
  ) VALUES (
    NEW.company_id, v_receipt.branch_id, v_supplier_id, v_order.supplier_name, v_receipt.order_id, v_receipt.id, v_line.product_id,
    v_type, v_priority, v_subject,
    'Recepcion ' || v_receipt.receipt_number || ', orden ' || v_order.order_number ||
      ': aceptado ' || v_receipt.accepted_quantity || ', rechazado ' || v_receipt.rejected_quantity ||
      ', pendiente ' || v_receipt.remaining_quantity || ', conciliacion ' || v_receipt.reconciliation_status || '.',
    v_claimed, CURRENT_DATE + CASE WHEN v_priority = 'urgent' THEN 1 ELSE 3 END, v_receipt.user_id
  ) ON CONFLICT (company_id, receipt_id) DO NOTHING RETURNING id INTO v_claim_id;

  IF v_claim_id IS NOT NULL THEN
    INSERT INTO public.supermarket_supplier_claim_events(
      company_id, branch_id, claim_id, actor_type, actor_id, idempotency_key, from_status, to_status, notes
    ) VALUES (NEW.company_id, v_receipt.branch_id, v_claim_id, 'system', v_receipt.user_id,
      'claim-open:' || v_claim_id::TEXT, NULL, 'open', 'Reclamo generado automaticamente desde la recepcion.');
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS supermarket_open_receipt_claim ON public.supermarket_purchase_receipt_lines;
CREATE TRIGGER supermarket_open_receipt_claim
  AFTER INSERT ON public.supermarket_purchase_receipt_lines
  FOR EACH ROW EXECUTE FUNCTION public.supermarket_open_receipt_claim();

CREATE OR REPLACE FUNCTION public.supermarket_queue_claim_edi()
RETURNS TRIGGER
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_catalog
AS $$
BEGIN
  INSERT INTO public.supermarket_edi_outbox(
    company_id, branch_id, event_type, claim_id, idempotency_key, payload
  ) VALUES (
    NEW.company_id, NEW.branch_id, 'COMDIS', NEW.id, 'COMDIS:' || NEW.id::TEXT || ':' || NEW.status,
    jsonb_build_object(
      'messageType', 'COMDIS', 'claimId', NEW.id, 'claimNumber', NEW.claim_number,
      'supplierId', NEW.supplier_id, 'supplierName', NEW.supplier_name,
      'orderId', NEW.order_id, 'receiptId', NEW.receipt_id, 'productId', NEW.product_id,
      'claimType', NEW.claim_type, 'status', NEW.status, 'priority', NEW.priority,
      'claimedQuantity', NEW.claimed_quantity, 'responseDueOn', NEW.response_due_on,
      'resolutionNotes', COALESCE(NEW.resolution_notes, ''), 'generatedAt', timezone('utc'::text, now())
    )
  ) ON CONFLICT (company_id, idempotency_key) DO NOTHING;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS supermarket_supplier_claim_edi ON public.supermarket_supplier_claims;
DROP TRIGGER IF EXISTS supermarket_supplier_claim_edi_insert ON public.supermarket_supplier_claims;
DROP TRIGGER IF EXISTS supermarket_supplier_claim_edi_update ON public.supermarket_supplier_claims;
CREATE TRIGGER supermarket_supplier_claim_edi_insert
  AFTER INSERT ON public.supermarket_supplier_claims
  FOR EACH ROW EXECUTE FUNCTION public.supermarket_queue_claim_edi();
CREATE TRIGGER supermarket_supplier_claim_edi_update
  AFTER UPDATE OF status ON public.supermarket_supplier_claims
  FOR EACH ROW WHEN (OLD.status IS DISTINCT FROM NEW.status)
  EXECUTE FUNCTION public.supermarket_queue_claim_edi();

CREATE OR REPLACE FUNCTION public.supermarket_list_supplier_claims(
  p_company_id UUID, p_branch_id UUID, p_supplier_id UUID DEFAULT NULL, p_status TEXT DEFAULT NULL
) RETURNS TABLE(
  id UUID, claim_number BIGINT, supplier_id UUID, supplier_name TEXT, order_id UUID, order_number BIGINT,
  receipt_id UUID, receipt_number BIGINT, product_id UUID, product_name TEXT, claim_type TEXT,
  status TEXT, priority TEXT, subject TEXT, description TEXT, claimed_quantity NUMERIC,
  response_due_on DATE, resolution_notes TEXT, event_count BIGINT,
  acknowledged_at TIMESTAMP WITH TIME ZONE, resolved_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE, updated_at TIMESTAMP WITH TIME ZONE
)
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public, pg_catalog
AS $$
BEGIN
  PERFORM public.supermarket_assert_scope(p_company_id, p_branch_id);
  IF p_status IS NOT NULL AND p_status NOT IN ('open', 'acknowledged', 'disputed', 'resolved') THEN
    RAISE EXCEPTION 'INVALID_CLAIM_STATUS';
  END IF;
  RETURN QUERY
  SELECT c.id, c.claim_number, c.supplier_id, c.supplier_name::TEXT, c.order_id, o.order_number,
    c.receipt_id, r.receipt_number, c.product_id, p.name::TEXT, c.claim_type::TEXT,
    c.status::TEXT, c.priority::TEXT, c.subject::TEXT, c.description,
    c.claimed_quantity, c.response_due_on, COALESCE(c.resolution_notes, '')::TEXT,
    (SELECT count(*) FROM public.supermarket_supplier_claim_events e
      WHERE e.company_id = c.company_id AND e.claim_id = c.id),
    c.acknowledged_at, c.resolved_at, c.created_at, c.updated_at
  FROM public.supermarket_supplier_claims c
  JOIN public.supermarket_purchase_orders o ON o.id = c.order_id AND o.company_id = c.company_id
  JOIN public.supermarket_purchase_receipts r ON r.id = c.receipt_id AND r.company_id = c.company_id
  JOIN public.products p ON p.id = c.product_id AND p.company_id = c.company_id
  WHERE c.company_id = p_company_id AND c.branch_id = p_branch_id
    AND (p_supplier_id IS NULL OR c.supplier_id = p_supplier_id)
    AND (p_status IS NULL OR c.status = p_status)
  ORDER BY CASE WHEN c.status = 'resolved' THEN 1 ELSE 0 END, c.response_due_on, c.created_at DESC
  LIMIT 2000;
END;
$$;

CREATE OR REPLACE FUNCTION public.supermarket_update_supplier_claim(
  p_company_id UUID, p_branch_id UUID, p_user_id UUID, p_claim_id UUID,
  p_idempotency_key TEXT, p_status TEXT, p_notes TEXT
) RETURNS JSONB
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_catalog
AS $$
DECLARE v_claim public.supermarket_supplier_claims%ROWTYPE; v_event public.supermarket_supplier_claim_events%ROWTYPE;
BEGIN
  PERFORM public.supermarket_assert_scope(p_company_id, p_branch_id);
  IF p_idempotency_key IS NULL OR length(p_idempotency_key) < 8 OR length(p_idempotency_key) > 128 THEN
    RAISE EXCEPTION 'INVALID_IDEMPOTENCY_KEY';
  END IF;
  IF p_status NOT IN ('acknowledged', 'disputed', 'resolved') OR length(COALESCE(p_notes, '')) > 2000 THEN
    RAISE EXCEPTION 'INVALID_CLAIM_UPDATE';
  END IF;
  PERFORM pg_advisory_xact_lock(hashtext(p_company_id::TEXT || ':' || p_idempotency_key));
  SELECT * INTO v_event FROM public.supermarket_supplier_claim_events
  WHERE company_id = p_company_id AND idempotency_key = p_idempotency_key;
  IF FOUND THEN RETURN jsonb_build_object('claimId', v_event.claim_id, 'status', v_event.to_status, 'duplicate', true); END IF;
  SELECT * INTO v_claim FROM public.supermarket_supplier_claims
  WHERE id = p_claim_id AND company_id = p_company_id AND branch_id = p_branch_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'SUPPLIER_CLAIM_NOT_FOUND'; END IF;
  IF v_claim.status = 'resolved' OR v_claim.status = p_status THEN RAISE EXCEPTION 'INVALID_CLAIM_TRANSITION'; END IF;
  UPDATE public.supermarket_supplier_claims SET status = p_status,
    acknowledged_at = CASE WHEN p_status = 'acknowledged' THEN COALESCE(acknowledged_at, timezone('utc'::text, now())) ELSE acknowledged_at END,
    resolved_at = CASE WHEN p_status = 'resolved' THEN timezone('utc'::text, now()) ELSE NULL END,
    resolution_notes = CASE WHEN p_status = 'resolved' THEN NULLIF(trim(p_notes), '') ELSE resolution_notes END,
    updated_at = timezone('utc'::text, now()) WHERE id = v_claim.id;
  INSERT INTO public.supermarket_supplier_claim_events(
    company_id, branch_id, claim_id, actor_type, actor_id, idempotency_key, from_status, to_status, notes
  ) VALUES (p_company_id, p_branch_id, v_claim.id, 'internal', p_user_id, p_idempotency_key,
    v_claim.status, p_status, NULLIF(trim(p_notes), ''));
  RETURN jsonb_build_object('claimId', v_claim.id, 'status', p_status, 'duplicate', false);
END;
$$;

CREATE OR REPLACE FUNCTION public.supermarket_supplier_portal_claims(p_token_hash TEXT)
RETURNS TABLE(
  id UUID, claim_number BIGINT, order_id UUID, order_number BIGINT, receipt_number BIGINT,
  product_name TEXT, claim_type TEXT, status TEXT, priority TEXT, subject TEXT, description TEXT,
  claimed_quantity NUMERIC, response_due_on DATE, resolution_notes TEXT,
  acknowledged_at TIMESTAMP WITH TIME ZONE, resolved_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE, updated_at TIMESTAMP WITH TIME ZONE
)
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public, pg_catalog
AS $$
DECLARE v_access public.supermarket_supplier_portal_access%ROWTYPE; v_supplier public.supermarket_suppliers%ROWTYPE;
BEGIN
  SELECT * INTO v_access FROM public.supermarket_supplier_portal_access
  WHERE token_hash = lower(p_token_hash) AND active AND expires_at > timezone('utc'::text, now());
  IF NOT FOUND THEN RAISE EXCEPTION 'INVALID_SUPPLIER_PORTAL_TOKEN'; END IF;
  SELECT s.* INTO v_supplier FROM public.supermarket_suppliers s
  WHERE s.id = v_access.supplier_id AND s.company_id = v_access.company_id AND s.active;
  IF NOT FOUND THEN RAISE EXCEPTION 'SUPPLIER_NOT_FOUND'; END IF;
  RETURN QUERY
  SELECT c.id, c.claim_number, c.order_id, o.order_number, r.receipt_number, p.name::TEXT,
    c.claim_type::TEXT, c.status::TEXT, c.priority::TEXT, c.subject::TEXT, c.description,
    c.claimed_quantity, c.response_due_on, COALESCE(c.resolution_notes, '')::TEXT,
    c.acknowledged_at, c.resolved_at, c.created_at, c.updated_at
  FROM public.supermarket_supplier_claims c
  JOIN public.supermarket_purchase_orders o ON o.id = c.order_id AND o.company_id = c.company_id
  JOIN public.supermarket_purchase_receipts r ON r.id = c.receipt_id AND r.company_id = c.company_id
  JOIN public.products p ON p.id = c.product_id AND p.company_id = c.company_id
  WHERE c.company_id = v_access.company_id AND c.branch_id = v_access.branch_id
    AND (c.supplier_id = v_supplier.id OR lower(trim(c.supplier_name)) = lower(trim(v_supplier.name)))
  ORDER BY CASE WHEN c.status = 'resolved' THEN 1 ELSE 0 END, c.response_due_on, c.created_at DESC
  LIMIT 500;
END;
$$;

CREATE OR REPLACE FUNCTION public.supermarket_supplier_respond_claim(
  p_token_hash TEXT, p_claim_id UUID, p_idempotency_key TEXT, p_status TEXT, p_notes TEXT
) RETURNS JSONB
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_catalog
AS $$
DECLARE v_access public.supermarket_supplier_portal_access%ROWTYPE; v_supplier public.supermarket_suppliers%ROWTYPE;
  v_claim public.supermarket_supplier_claims%ROWTYPE; v_event public.supermarket_supplier_claim_events%ROWTYPE;
BEGIN
  IF p_idempotency_key IS NULL OR length(p_idempotency_key) < 8 OR length(p_idempotency_key) > 128
    OR p_status NOT IN ('acknowledged', 'disputed') OR length(COALESCE(p_notes, '')) > 2000 THEN
    RAISE EXCEPTION 'INVALID_CLAIM_RESPONSE';
  END IF;
  SELECT * INTO v_access FROM public.supermarket_supplier_portal_access
  WHERE token_hash = lower(p_token_hash) AND active AND expires_at > timezone('utc'::text, now());
  IF NOT FOUND THEN RAISE EXCEPTION 'INVALID_SUPPLIER_PORTAL_TOKEN'; END IF;
  SELECT s.* INTO v_supplier FROM public.supermarket_suppliers s
  WHERE s.id = v_access.supplier_id AND s.company_id = v_access.company_id AND s.active;
  IF NOT FOUND THEN RAISE EXCEPTION 'SUPPLIER_NOT_FOUND'; END IF;
  PERFORM pg_advisory_xact_lock(hashtext(v_access.company_id::TEXT || ':' || p_idempotency_key));
  SELECT * INTO v_event FROM public.supermarket_supplier_claim_events
  WHERE company_id = v_access.company_id AND idempotency_key = p_idempotency_key;
  IF FOUND THEN RETURN jsonb_build_object('claimId', v_event.claim_id, 'status', v_event.to_status, 'duplicate', true); END IF;
  SELECT * INTO v_claim FROM public.supermarket_supplier_claims
  WHERE id = p_claim_id AND company_id = v_access.company_id AND branch_id = v_access.branch_id
    AND (supplier_id = v_supplier.id OR lower(trim(supplier_name)) = lower(trim(v_supplier.name))) FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'SUPPLIER_CLAIM_NOT_FOUND'; END IF;
  IF v_claim.status = 'resolved' OR v_claim.status = p_status THEN RAISE EXCEPTION 'INVALID_CLAIM_TRANSITION'; END IF;
  UPDATE public.supermarket_supplier_claims SET status = p_status,
    acknowledged_at = CASE WHEN p_status = 'acknowledged' THEN COALESCE(acknowledged_at, timezone('utc'::text, now())) ELSE acknowledged_at END,
    updated_at = timezone('utc'::text, now()) WHERE id = v_claim.id;
  INSERT INTO public.supermarket_supplier_claim_events(
    company_id, branch_id, claim_id, actor_type, actor_id, idempotency_key, from_status, to_status, notes
  ) VALUES (v_access.company_id, v_access.branch_id, v_claim.id, 'supplier', v_supplier.id,
    p_idempotency_key, v_claim.status, p_status, NULLIF(trim(p_notes), ''));
  RETURN jsonb_build_object('claimId', v_claim.id, 'status', p_status, 'duplicate', false);
END;
$$;

REVOKE ALL ON FUNCTION public.supermarket_list_supplier_claims(UUID, UUID, UUID, TEXT) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.supermarket_update_supplier_claim(UUID, UUID, UUID, UUID, TEXT, TEXT, TEXT) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.supermarket_supplier_portal_claims(TEXT) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.supermarket_supplier_respond_claim(TEXT, UUID, TEXT, TEXT, TEXT) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.supermarket_list_supplier_claims(UUID, UUID, UUID, TEXT) TO service_role;
GRANT EXECUTE ON FUNCTION public.supermarket_update_supplier_claim(UUID, UUID, UUID, UUID, TEXT, TEXT, TEXT) TO service_role;
GRANT EXECUTE ON FUNCTION public.supermarket_supplier_portal_claims(TEXT) TO service_role;
GRANT EXECUTE ON FUNCTION public.supermarket_supplier_respond_claim(TEXT, UUID, TEXT, TEXT, TEXT) TO service_role;
