-- Gastronomy domain: catalog, recipes, dining room and orders.

WITH permission_definitions(name, description) AS (
  VALUES
    ('gastronomy.catalog.read', 'View the gastronomy menu'),
    ('gastronomy.catalog.write', 'Create and update menu items'),
    ('gastronomy.inventory.read', 'View ingredients and stock'),
    ('gastronomy.inventory.write', 'Manage ingredients and stock'),
    ('gastronomy.recipes.read', 'View recipes and costs'),
    ('gastronomy.recipes.write', 'Manage recipes and consumption'),
    ('gastronomy.orders.read', 'View tables, orders and kitchen status'),
    ('gastronomy.orders.write', 'Create and update orders'),
    ('gastronomy.orders.close', 'Close, cancel and settle orders')
)
INSERT INTO public.permissions(module_id, name, description)
SELECT m.id, d.name, d.description
FROM permission_definitions d
JOIN public.modules m ON m.code = 'gastronomy_tables'
ON CONFLICT (name) DO UPDATE SET description = EXCLUDED.description;

CREATE TABLE IF NOT EXISTS public.gastronomy_menu_items (
  product_id UUID PRIMARY KEY REFERENCES public.products(id) ON DELETE CASCADE,
  company_id UUID REFERENCES public.companies(id) ON DELETE CASCADE NOT NULL,
  category VARCHAR(100) NOT NULL,
  preparation_station VARCHAR(50) DEFAULT 'kitchen' NOT NULL,
  active BOOLEAN DEFAULT true NOT NULL,
  sort_order INTEGER DEFAULT 0 NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.gastronomy_ingredients (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID REFERENCES public.companies(id) ON DELETE CASCADE NOT NULL,
  name VARCHAR(255) NOT NULL,
  unit VARCHAR(30) NOT NULL,
  current_stock NUMERIC(14, 3) DEFAULT 0 NOT NULL CHECK (current_stock >= 0),
  minimum_stock NUMERIC(14, 3) DEFAULT 0 NOT NULL CHECK (minimum_stock >= 0),
  cost_per_unit NUMERIC(14, 4) DEFAULT 0 NOT NULL CHECK (cost_per_unit >= 0),
  supplier_name VARCHAR(255),
  active BOOLEAN DEFAULT true NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(company_id, name)
);

CREATE TABLE IF NOT EXISTS public.gastronomy_recipes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID REFERENCES public.companies(id) ON DELETE CASCADE NOT NULL,
  product_id UUID REFERENCES public.products(id) ON DELETE CASCADE NOT NULL,
  portions NUMERIC(12, 3) DEFAULT 1 NOT NULL CHECK (portions > 0),
  instructions TEXT,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(company_id, product_id)
);

CREATE TABLE IF NOT EXISTS public.gastronomy_recipe_lines (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID REFERENCES public.companies(id) ON DELETE CASCADE NOT NULL,
  recipe_id UUID REFERENCES public.gastronomy_recipes(id) ON DELETE CASCADE NOT NULL,
  ingredient_id UUID REFERENCES public.gastronomy_ingredients(id) ON DELETE RESTRICT NOT NULL,
  quantity NUMERIC(14, 4) NOT NULL CHECK (quantity > 0),
  waste_percentage NUMERIC(5, 2) DEFAULT 0 NOT NULL CHECK (waste_percentage BETWEEN 0 AND 100),
  UNIQUE(recipe_id, ingredient_id)
);

CREATE TABLE IF NOT EXISTS public.gastronomy_dining_areas (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID REFERENCES public.companies(id) ON DELETE CASCADE NOT NULL,
  branch_id UUID REFERENCES public.branches(id) ON DELETE CASCADE NOT NULL,
  name VARCHAR(100) NOT NULL,
  sort_order INTEGER DEFAULT 0 NOT NULL,
  active BOOLEAN DEFAULT true NOT NULL,
  UNIQUE(branch_id, name)
);

CREATE TABLE IF NOT EXISTS public.gastronomy_dining_tables (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID REFERENCES public.companies(id) ON DELETE CASCADE NOT NULL,
  branch_id UUID REFERENCES public.branches(id) ON DELETE CASCADE NOT NULL,
  area_id UUID REFERENCES public.gastronomy_dining_areas(id) ON DELETE CASCADE NOT NULL,
  name VARCHAR(50) NOT NULL,
  capacity INTEGER DEFAULT 2 NOT NULL CHECK (capacity > 0),
  status VARCHAR(20) DEFAULT 'available' NOT NULL CHECK (status IN ('available', 'occupied', 'reserved', 'cleaning', 'blocked')),
  UNIQUE(branch_id, name)
);

CREATE TABLE IF NOT EXISTS public.gastronomy_orders (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID REFERENCES public.companies(id) ON DELETE CASCADE NOT NULL,
  branch_id UUID REFERENCES public.branches(id) ON DELETE RESTRICT NOT NULL,
  table_id UUID REFERENCES public.gastronomy_dining_tables(id) ON DELETE SET NULL,
  user_id UUID NOT NULL,
  order_number BIGINT GENERATED BY DEFAULT AS IDENTITY,
  channel VARCHAR(20) DEFAULT 'dine_in' NOT NULL CHECK (channel IN ('dine_in', 'takeaway', 'delivery')),
  status VARCHAR(30) DEFAULT 'open' NOT NULL CHECK (status IN ('open', 'sent', 'preparing', 'ready', 'served', 'closed', 'cancelled')),
  customer_name VARCHAR(255),
  notes TEXT,
  subtotal NUMERIC(14, 2) DEFAULT 0 NOT NULL,
  total NUMERIC(14, 2) DEFAULT 0 NOT NULL,
  version INTEGER DEFAULT 1 NOT NULL,
  opened_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  closed_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS public.gastronomy_order_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID REFERENCES public.companies(id) ON DELETE CASCADE NOT NULL,
  order_id UUID REFERENCES public.gastronomy_orders(id) ON DELETE CASCADE NOT NULL,
  product_id UUID REFERENCES public.products(id) ON DELETE RESTRICT NOT NULL,
  quantity NUMERIC(12, 3) NOT NULL CHECK (quantity > 0),
  unit_price NUMERIC(14, 2) NOT NULL CHECK (unit_price >= 0),
  status VARCHAR(30) DEFAULT 'pending' NOT NULL CHECK (status IN ('pending', 'sent', 'preparing', 'ready', 'served', 'cancelled')),
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_gastronomy_menu_company ON public.gastronomy_menu_items(company_id, active, sort_order);
CREATE INDEX IF NOT EXISTS idx_gastronomy_ingredients_company ON public.gastronomy_ingredients(company_id, active, name);
CREATE INDEX IF NOT EXISTS idx_gastronomy_recipes_company ON public.gastronomy_recipes(company_id, product_id);
CREATE INDEX IF NOT EXISTS idx_gastronomy_recipe_lines_company ON public.gastronomy_recipe_lines(company_id, recipe_id);
CREATE INDEX IF NOT EXISTS idx_gastronomy_tables_branch_status ON public.gastronomy_dining_tables(company_id, branch_id, status);
CREATE INDEX IF NOT EXISTS idx_gastronomy_orders_open ON public.gastronomy_orders(company_id, branch_id, status, opened_at DESC);
CREATE INDEX IF NOT EXISTS idx_gastronomy_order_items_order ON public.gastronomy_order_items(company_id, order_id);

ALTER TABLE public.gastronomy_menu_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gastronomy_ingredients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gastronomy_recipes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gastronomy_recipe_lines ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gastronomy_dining_areas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gastronomy_dining_tables ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gastronomy_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gastronomy_order_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Gastronomy menu by company" ON public.gastronomy_menu_items FOR ALL
  USING (company_id = public.jwt_company_id() AND public.jwt_business_type() = 'gastronomy')
  WITH CHECK (company_id = public.jwt_company_id() AND public.jwt_business_type() = 'gastronomy');
CREATE POLICY "Gastronomy ingredients by company" ON public.gastronomy_ingredients FOR ALL
  USING (company_id = public.jwt_company_id() AND public.jwt_business_type() = 'gastronomy')
  WITH CHECK (company_id = public.jwt_company_id() AND public.jwt_business_type() = 'gastronomy');
CREATE POLICY "Gastronomy recipes by company" ON public.gastronomy_recipes FOR ALL
  USING (company_id = public.jwt_company_id() AND public.jwt_business_type() = 'gastronomy')
  WITH CHECK (company_id = public.jwt_company_id() AND public.jwt_business_type() = 'gastronomy');
CREATE POLICY "Gastronomy recipe lines by company" ON public.gastronomy_recipe_lines FOR ALL
  USING (company_id = public.jwt_company_id() AND public.jwt_business_type() = 'gastronomy')
  WITH CHECK (company_id = public.jwt_company_id() AND public.jwt_business_type() = 'gastronomy');
CREATE POLICY "Gastronomy areas by company" ON public.gastronomy_dining_areas FOR ALL
  USING (company_id = public.jwt_company_id() AND public.jwt_business_type() = 'gastronomy')
  WITH CHECK (company_id = public.jwt_company_id() AND public.jwt_business_type() = 'gastronomy');
CREATE POLICY "Gastronomy tables by company" ON public.gastronomy_dining_tables FOR ALL
  USING (company_id = public.jwt_company_id() AND public.jwt_business_type() = 'gastronomy')
  WITH CHECK (company_id = public.jwt_company_id() AND public.jwt_business_type() = 'gastronomy');
CREATE POLICY "Gastronomy orders by company" ON public.gastronomy_orders FOR ALL
  USING (company_id = public.jwt_company_id() AND public.jwt_business_type() = 'gastronomy')
  WITH CHECK (company_id = public.jwt_company_id() AND public.jwt_business_type() = 'gastronomy');
CREATE POLICY "Gastronomy order items by company" ON public.gastronomy_order_items FOR ALL
  USING (company_id = public.jwt_company_id() AND public.jwt_business_type() = 'gastronomy')
  WITH CHECK (company_id = public.jwt_company_id() AND public.jwt_business_type() = 'gastronomy');

CREATE OR REPLACE FUNCTION public.gastronomy_list_menu(p_company_id UUID)
RETURNS TABLE(
  id UUID, name TEXT, description TEXT, category TEXT, sku TEXT, price NUMERIC,
  cost NUMERIC, stock NUMERIC, min_stock NUMERIC, vat_rate NUMERIC,
  active BOOLEAN, image_url TEXT, created_at TIMESTAMP WITH TIME ZONE
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT
    p.id,
    p.name::TEXT,
    COALESCE(p.description, '')::TEXT,
    g.category::TEXT,
    COALESCE(p.sku, '')::TEXT,
    p.price,
    p.cost,
    COALESCE((SELECT SUM(s.quantity) FROM public.stock s WHERE s.company_id = p_company_id AND s.product_id = p.id), 0),
    COALESCE((SELECT MAX(s.min_stock) FROM public.stock s WHERE s.company_id = p_company_id AND s.product_id = p.id), 0),
    p.vat_rate,
    g.active,
    p.image_url,
    p.created_at
  FROM public.gastronomy_menu_items g
  JOIN public.products p ON p.id = g.product_id AND p.company_id = g.company_id
  WHERE g.company_id = p_company_id
  ORDER BY g.sort_order, p.name;
$$;

CREATE OR REPLACE FUNCTION public.gastronomy_save_menu_item(
  p_company_id UUID,
  p_user_id UUID,
  p_branch_id UUID,
  p_product_id UUID,
  p_name TEXT,
  p_description TEXT,
  p_category TEXT,
  p_sku TEXT,
  p_price NUMERIC,
  p_cost NUMERIC,
  p_stock NUMERIC,
  p_min_stock NUMERIC,
  p_vat_rate NUMERIC,
  p_active BOOLEAN,
  p_image_url TEXT
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_catalog
AS $$
DECLARE
  v_product_id UUID := p_product_id;
  v_stock_id UUID;
  v_previous_stock NUMERIC := 0;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM public.companies c
    JOIN public.business_types bt ON bt.id = c.business_type_id
    WHERE c.id = p_company_id AND c.status = 'active' AND bt.code = 'gastronomy'
  ) THEN
    RAISE EXCEPTION 'INVALID_GASTRONOMY_COMPANY';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM public.branches b WHERE b.id = p_branch_id AND b.company_id = p_company_id) THEN
    RAISE EXCEPTION 'BRANCH_COMPANY_MISMATCH';
  END IF;

  IF v_product_id IS NULL THEN
    INSERT INTO public.products(company_id, name, description, sku, price, cost, vat_rate, image_url)
    VALUES (p_company_id, p_name, p_description, p_sku, p_price, p_cost, p_vat_rate, p_image_url)
    RETURNING id INTO v_product_id;
  ELSE
    UPDATE public.products SET
      name = p_name,
      description = p_description,
      sku = p_sku,
      price = p_price,
      cost = p_cost,
      vat_rate = p_vat_rate,
      image_url = p_image_url
    WHERE id = v_product_id AND company_id = p_company_id;
    IF NOT FOUND THEN RAISE EXCEPTION 'PRODUCT_NOT_FOUND'; END IF;
  END IF;

  INSERT INTO public.gastronomy_menu_items(product_id, company_id, category, active)
  VALUES (v_product_id, p_company_id, p_category, p_active)
  ON CONFLICT (product_id) DO UPDATE SET
    category = EXCLUDED.category,
    active = EXCLUDED.active,
    updated_at = timezone('utc'::text, now());

  SELECT s.id, s.quantity INTO v_stock_id, v_previous_stock
  FROM public.stock s
  WHERE s.company_id = p_company_id AND s.branch_id = p_branch_id AND s.product_id = v_product_id;

  IF v_stock_id IS NULL THEN
    INSERT INTO public.stock(company_id, branch_id, product_id, quantity, min_stock)
    VALUES (p_company_id, p_branch_id, v_product_id, p_stock, p_min_stock)
    RETURNING id INTO v_stock_id;
  ELSE
    UPDATE public.stock SET quantity = p_stock, min_stock = p_min_stock WHERE id = v_stock_id;
  END IF;

  IF p_stock IS DISTINCT FROM v_previous_stock THEN
    INSERT INTO public.stock_movements(company_id, stock_id, user_id, quantity, type, notes)
    VALUES (p_company_id, v_stock_id, p_user_id, p_stock - v_previous_stock, 'catalog_adjustment', 'Gastronomy menu editor');
  END IF;
  RETURN v_product_id;
EXCEPTION
  WHEN unique_violation THEN RAISE EXCEPTION 'SKU_ALREADY_EXISTS';
END;
$$;

REVOKE ALL ON FUNCTION public.gastronomy_list_menu(UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.gastronomy_save_menu_item(UUID, UUID, UUID, UUID, TEXT, TEXT, TEXT, TEXT, NUMERIC, NUMERIC, NUMERIC, NUMERIC, NUMERIC, BOOLEAN, TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.gastronomy_list_menu(UUID) TO service_role;
GRANT EXECUTE ON FUNCTION public.gastronomy_save_menu_item(UUID, UUID, UUID, UUID, TEXT, TEXT, TEXT, TEXT, NUMERIC, NUMERIC, NUMERIC, NUMERIC, NUMERIC, BOOLEAN, TEXT) TO service_role;
