-- Supermarket domain: persistent catalog, purchasing and FEFO lot traceability.

WITH permission_definitions(name, description) AS (
  VALUES
    ('supermarket.catalog.read', 'View supermarket products and prices'),
    ('supermarket.catalog.write', 'Create and update supermarket products'),
    ('supermarket.inventory.read', 'View supermarket stock and lots'),
    ('supermarket.inventory.write', 'Adjust supermarket stock'),
    ('supermarket.purchases.read', 'View supermarket purchase orders'),
    ('supermarket.purchases.write', 'Create and update supermarket purchase orders'),
    ('supermarket.purchases.receive', 'Receive merchandise and create stock lots'),
    ('supermarket.sales.create', 'Commit supermarket sales and stock consumption')
)
INSERT INTO public.permissions(module_id, name, description)
SELECT m.id, d.name, d.description
FROM permission_definitions d
JOIN public.modules m ON m.code = 'barcode_scanner'
ON CONFLICT (name) DO UPDATE SET description = EXCLUDED.description;

CREATE TABLE IF NOT EXISTS public.supermarket_products (
  product_id UUID PRIMARY KEY REFERENCES public.products(id) ON DELETE CASCADE,
  company_id UUID REFERENCES public.companies(id) ON DELETE CASCADE NOT NULL,
  category VARCHAR(40) NOT NULL,
  unit VARCHAR(10) DEFAULT 'unit' NOT NULL CHECK (unit IN ('unit', 'kg')),
  is_weighed BOOLEAN DEFAULT false NOT NULL,
  promo VARCHAR(20) DEFAULT 'none' NOT NULL CHECK (promo IN ('none', '2x1', '30off')),
  supplier_name VARCHAR(255),
  active BOOLEAN DEFAULT true NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.supermarket_purchase_orders (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID REFERENCES public.companies(id) ON DELETE CASCADE NOT NULL,
  branch_id UUID REFERENCES public.branches(id) ON DELETE RESTRICT NOT NULL,
  order_number BIGINT GENERATED BY DEFAULT AS IDENTITY,
  supplier_name VARCHAR(255) NOT NULL,
  expected_on DATE,
  status VARCHAR(20) DEFAULT 'draft' NOT NULL CHECK (status IN ('draft', 'ordered', 'received', 'cancelled')),
  created_by UUID NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  received_at TIMESTAMP WITH TIME ZONE,
  UNIQUE(company_id, order_number)
);

CREATE TABLE IF NOT EXISTS public.supermarket_purchase_order_lines (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID REFERENCES public.companies(id) ON DELETE CASCADE NOT NULL,
  order_id UUID REFERENCES public.supermarket_purchase_orders(id) ON DELETE CASCADE NOT NULL,
  product_id UUID REFERENCES public.products(id) ON DELETE RESTRICT NOT NULL,
  quantity NUMERIC(14, 3) NOT NULL CHECK (quantity > 0),
  unit_cost NUMERIC(14, 4) DEFAULT 0 NOT NULL CHECK (unit_cost >= 0),
  lot_code VARCHAR(100),
  expiration_date DATE,
  UNIQUE(order_id, product_id)
);

CREATE TABLE IF NOT EXISTS public.supermarket_stock_lots (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID REFERENCES public.companies(id) ON DELETE CASCADE NOT NULL,
  branch_id UUID REFERENCES public.branches(id) ON DELETE RESTRICT NOT NULL,
  product_id UUID REFERENCES public.products(id) ON DELETE RESTRICT NOT NULL,
  purchase_order_line_id UUID REFERENCES public.supermarket_purchase_order_lines(id) ON DELETE SET NULL,
  lot_code VARCHAR(100) NOT NULL,
  quantity_received NUMERIC(14, 3) NOT NULL CHECK (quantity_received > 0),
  quantity_remaining NUMERIC(14, 3) NOT NULL CHECK (quantity_remaining >= 0),
  expiration_date DATE,
  received_on DATE DEFAULT CURRENT_DATE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(company_id, branch_id, product_id, lot_code)
);

CREATE INDEX IF NOT EXISTS idx_supermarket_products_company
  ON public.supermarket_products(company_id, active, category, product_id);
CREATE INDEX IF NOT EXISTS idx_supermarket_purchases_branch_status
  ON public.supermarket_purchase_orders(company_id, branch_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_supermarket_purchase_lines_order
  ON public.supermarket_purchase_order_lines(company_id, order_id, product_id);
CREATE INDEX IF NOT EXISTS idx_supermarket_lots_fefo
  ON public.supermarket_stock_lots(company_id, branch_id, product_id, expiration_date, quantity_remaining)
  WHERE quantity_remaining > 0;
ALTER TABLE public.supermarket_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.supermarket_purchase_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.supermarket_purchase_order_lines ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.supermarket_stock_lots ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Supermarket products by company" ON public.supermarket_products FOR ALL
  USING (company_id = public.jwt_company_id() AND public.jwt_business_type() = 'supermarket')
  WITH CHECK (company_id = public.jwt_company_id() AND public.jwt_business_type() = 'supermarket');
CREATE POLICY "Supermarket purchases by company" ON public.supermarket_purchase_orders FOR ALL
  USING (company_id = public.jwt_company_id() AND public.jwt_business_type() = 'supermarket')
  WITH CHECK (company_id = public.jwt_company_id() AND public.jwt_business_type() = 'supermarket');
CREATE POLICY "Supermarket purchase lines by company" ON public.supermarket_purchase_order_lines FOR ALL
  USING (company_id = public.jwt_company_id() AND public.jwt_business_type() = 'supermarket')
  WITH CHECK (company_id = public.jwt_company_id() AND public.jwt_business_type() = 'supermarket');
CREATE POLICY "Supermarket lots by company" ON public.supermarket_stock_lots FOR ALL
  USING (company_id = public.jwt_company_id() AND public.jwt_business_type() = 'supermarket')
  WITH CHECK (company_id = public.jwt_company_id() AND public.jwt_business_type() = 'supermarket');

CREATE OR REPLACE FUNCTION public.supermarket_assert_scope(p_company_id UUID, p_branch_id UUID)
RETURNS VOID
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, pg_catalog
AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM public.companies c
    JOIN public.business_types bt ON bt.id = c.business_type_id
    WHERE c.id = p_company_id AND c.status = 'active' AND bt.code = 'supermarket'
  ) THEN
    RAISE EXCEPTION 'INVALID_SUPERMARKET_COMPANY';
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM public.branches b
    WHERE b.id = p_branch_id AND b.company_id = p_company_id
  ) THEN
    RAISE EXCEPTION 'BRANCH_COMPANY_MISMATCH';
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.supermarket_list_products(p_company_id UUID, p_branch_id UUID)
RETURNS TABLE(
  id UUID, name TEXT, price NUMERIC, cost NUMERIC, barcode TEXT, is_weighed BOOLEAN,
  unit TEXT, category TEXT, expiration_date DATE, promo TEXT, stock NUMERIC,
  min_stock NUMERIC, supplier TEXT, image_url TEXT, active BOOLEAN
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, pg_catalog
AS $$
BEGIN
  PERFORM public.supermarket_assert_scope(p_company_id, p_branch_id);
  RETURN QUERY
  SELECT
    p.id,
    p.name::TEXT,
    p.price,
    p.cost,
    COALESCE(p.barcode, '')::TEXT,
    sp.is_weighed,
    sp.unit::TEXT,
    sp.category::TEXT,
    (
      SELECT sl.expiration_date
      FROM public.supermarket_stock_lots sl
      WHERE sl.company_id = p_company_id
        AND sl.branch_id = p_branch_id
        AND sl.product_id = p.id
        AND sl.quantity_remaining > 0
      ORDER BY sl.expiration_date ASC NULLS LAST, sl.received_on ASC
      LIMIT 1
    ),
    sp.promo::TEXT,
    COALESCE(s.quantity, 0),
    COALESCE(s.min_stock, 0),
    COALESCE(sp.supplier_name, '')::TEXT,
    p.image_url,
    sp.active
  FROM public.supermarket_products sp
  JOIN public.products p ON p.id = sp.product_id AND p.company_id = sp.company_id
  LEFT JOIN public.stock s
    ON s.company_id = p_company_id AND s.branch_id = p_branch_id AND s.product_id = p.id
  WHERE sp.company_id = p_company_id
  ORDER BY p.name;
END;
$$;

CREATE OR REPLACE FUNCTION public.supermarket_save_product(
  p_company_id UUID,
  p_branch_id UUID,
  p_user_id UUID,
  p_product_id UUID,
  p_name TEXT,
  p_barcode TEXT,
  p_price NUMERIC,
  p_cost NUMERIC,
  p_stock NUMERIC,
  p_min_stock NUMERIC,
  p_category TEXT,
  p_unit TEXT,
  p_is_weighed BOOLEAN,
  p_promo TEXT,
  p_supplier TEXT,
  p_image_url TEXT,
  p_active BOOLEAN
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_catalog
AS $$
DECLARE
  v_product_id UUID := p_product_id;
  v_stock_id UUID;
  v_previous_stock NUMERIC := 0;
BEGIN
  PERFORM public.supermarket_assert_scope(p_company_id, p_branch_id);
  IF p_name IS NULL OR trim(p_name) = '' OR p_barcode IS NULL OR trim(p_barcode) = '' THEN
    RAISE EXCEPTION 'INVALID_PRODUCT';
  END IF;
  IF p_price < 0 OR p_cost < 0 OR p_stock < 0 OR p_min_stock < 0 THEN
    RAISE EXCEPTION 'INVALID_AMOUNT';
  END IF;
  IF p_unit NOT IN ('unit', 'kg') OR p_promo NOT IN ('none', '2x1', '30off') THEN
    RAISE EXCEPTION 'INVALID_PRODUCT_ATTRIBUTES';
  END IF;

  IF v_product_id IS NULL THEN
    INSERT INTO public.products(
      company_id, name, sku, barcode, price, cost, vat_rate, is_service, stock_control, image_url
    ) VALUES (
      p_company_id, trim(p_name), trim(p_barcode), trim(p_barcode), p_price, p_cost, 21, false, true, p_image_url
    ) RETURNING id INTO v_product_id;
  ELSE
    UPDATE public.products SET
      name = trim(p_name),
      sku = trim(p_barcode),
      barcode = trim(p_barcode),
      price = p_price,
      cost = p_cost,
      image_url = p_image_url,
      updated_at = timezone('utc'::text, now())
    WHERE id = v_product_id AND company_id = p_company_id;
    IF NOT FOUND THEN RAISE EXCEPTION 'PRODUCT_NOT_FOUND'; END IF;
  END IF;

  INSERT INTO public.supermarket_products(
    product_id, company_id, category, unit, is_weighed, promo, supplier_name, active
  ) VALUES (
    v_product_id, p_company_id, trim(p_category), p_unit, p_is_weighed, p_promo,
    NULLIF(trim(p_supplier), ''), p_active
  )
  ON CONFLICT (product_id) DO UPDATE SET
    category = EXCLUDED.category,
    unit = EXCLUDED.unit,
    is_weighed = EXCLUDED.is_weighed,
    promo = EXCLUDED.promo,
    supplier_name = EXCLUDED.supplier_name,
    active = EXCLUDED.active,
    updated_at = timezone('utc'::text, now());

  SELECT s.id, s.quantity INTO v_stock_id, v_previous_stock
  FROM public.stock s
  WHERE s.company_id = p_company_id AND s.branch_id = p_branch_id AND s.product_id = v_product_id
  FOR UPDATE;

  IF v_stock_id IS NULL THEN
    INSERT INTO public.stock(company_id, branch_id, product_id, quantity, min_stock)
    VALUES (p_company_id, p_branch_id, v_product_id, p_stock, p_min_stock)
    RETURNING id INTO v_stock_id;
  ELSE
    UPDATE public.stock SET quantity = p_stock, min_stock = p_min_stock WHERE id = v_stock_id;
  END IF;

  IF p_stock IS DISTINCT FROM v_previous_stock THEN
    INSERT INTO public.stock_movements(company_id, stock_id, user_id, quantity, type, notes)
    VALUES (p_company_id, v_stock_id, p_user_id, p_stock - v_previous_stock, 'supermarket_adjustment', 'Supermarket catalog editor');
  END IF;
  RETURN v_product_id;
EXCEPTION
  WHEN unique_violation THEN RAISE EXCEPTION 'BARCODE_ALREADY_EXISTS';
END;
$$;

CREATE OR REPLACE FUNCTION public.supermarket_list_purchases(p_company_id UUID, p_branch_id UUID)
RETURNS TABLE(
  id UUID, supplier TEXT, product_id UUID, quantity NUMERIC, unit_cost NUMERIC,
  expected_date DATE, status TEXT, lot_code TEXT, expiration_date DATE
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, pg_catalog
AS $$
BEGIN
  PERFORM public.supermarket_assert_scope(p_company_id, p_branch_id);
  RETURN QUERY
  SELECT
    po.id,
    po.supplier_name::TEXT,
    pol.product_id,
    pol.quantity,
    pol.unit_cost,
    po.expected_on,
    po.status::TEXT,
    COALESCE(pol.lot_code, '')::TEXT,
    pol.expiration_date
  FROM public.supermarket_purchase_orders po
  JOIN public.supermarket_purchase_order_lines pol
    ON pol.order_id = po.id AND pol.company_id = po.company_id
  WHERE po.company_id = p_company_id AND po.branch_id = p_branch_id
  ORDER BY po.created_at DESC;
END;
$$;

CREATE OR REPLACE FUNCTION public.supermarket_save_purchase(
  p_company_id UUID,
  p_branch_id UUID,
  p_user_id UUID,
  p_order_id UUID,
  p_supplier TEXT,
  p_product_id UUID,
  p_quantity NUMERIC,
  p_unit_cost NUMERIC,
  p_expected_date DATE,
  p_status TEXT,
  p_lot_code TEXT,
  p_expiration_date DATE
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_catalog
AS $$
DECLARE
  v_order_id UUID := p_order_id;
BEGIN
  PERFORM public.supermarket_assert_scope(p_company_id, p_branch_id);
  IF p_status NOT IN ('draft', 'ordered') OR p_quantity <= 0 OR p_unit_cost < 0 THEN
    RAISE EXCEPTION 'INVALID_PURCHASE';
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM public.supermarket_products sp
    WHERE sp.company_id = p_company_id AND sp.product_id = p_product_id
  ) THEN
    RAISE EXCEPTION 'PRODUCT_NOT_FOUND';
  END IF;

  IF v_order_id IS NULL THEN
    INSERT INTO public.supermarket_purchase_orders(
      company_id, branch_id, supplier_name, expected_on, status, created_by
    ) VALUES (
      p_company_id, p_branch_id, trim(p_supplier), p_expected_date, p_status, p_user_id
    ) RETURNING id INTO v_order_id;
  ELSE
    UPDATE public.supermarket_purchase_orders SET
      supplier_name = trim(p_supplier),
      expected_on = p_expected_date,
      status = p_status,
      updated_at = timezone('utc'::text, now())
    WHERE id = v_order_id AND company_id = p_company_id AND branch_id = p_branch_id
      AND status IN ('draft', 'ordered');
    IF NOT FOUND THEN RAISE EXCEPTION 'PURCHASE_NOT_EDITABLE'; END IF;
    DELETE FROM public.supermarket_purchase_order_lines
    WHERE order_id = v_order_id AND company_id = p_company_id;
  END IF;

  INSERT INTO public.supermarket_purchase_order_lines(
    company_id, order_id, product_id, quantity, unit_cost, lot_code, expiration_date
  ) VALUES (
    p_company_id, v_order_id, p_product_id, p_quantity, p_unit_cost,
    NULLIF(trim(p_lot_code), ''), p_expiration_date
  );
  RETURN v_order_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.supermarket_receive_purchase(
  p_company_id UUID,
  p_branch_id UUID,
  p_user_id UUID,
  p_order_id UUID
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_catalog
AS $$
DECLARE
  v_order public.supermarket_purchase_orders%ROWTYPE;
  v_line public.supermarket_purchase_order_lines%ROWTYPE;
  v_stock_id UUID;
  v_current_stock NUMERIC := 0;
  v_current_cost NUMERIC := 0;
  v_lot_code TEXT;
BEGIN
  PERFORM public.supermarket_assert_scope(p_company_id, p_branch_id);
  SELECT * INTO v_order
  FROM public.supermarket_purchase_orders
  WHERE id = p_order_id AND company_id = p_company_id AND branch_id = p_branch_id
  FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'PURCHASE_NOT_FOUND'; END IF;
  IF v_order.status = 'received' THEN RETURN v_order.id; END IF;
  IF v_order.status = 'cancelled' THEN RAISE EXCEPTION 'PURCHASE_NOT_RECEIVABLE'; END IF;

  SELECT * INTO v_line
  FROM public.supermarket_purchase_order_lines
  WHERE order_id = v_order.id AND company_id = p_company_id
  FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'PURCHASE_LINE_NOT_FOUND'; END IF;

  SELECT p.cost INTO v_current_cost
  FROM public.products p
  WHERE p.id = v_line.product_id AND p.company_id = p_company_id
  FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'PRODUCT_NOT_FOUND'; END IF;

  SELECT s.id, s.quantity INTO v_stock_id, v_current_stock
  FROM public.stock s
  WHERE s.company_id = p_company_id AND s.branch_id = p_branch_id AND s.product_id = v_line.product_id
  FOR UPDATE;

  IF v_stock_id IS NULL THEN
    INSERT INTO public.stock(company_id, branch_id, product_id, quantity, min_stock)
    VALUES (p_company_id, p_branch_id, v_line.product_id, v_line.quantity, 0)
    RETURNING id INTO v_stock_id;
  ELSE
    UPDATE public.stock SET quantity = quantity + v_line.quantity WHERE id = v_stock_id;
  END IF;

  UPDATE public.products SET
    cost = CASE
      WHEN v_current_stock + v_line.quantity = 0 THEN v_line.unit_cost
      ELSE ROUND(((v_current_stock * v_current_cost) + (v_line.quantity * v_line.unit_cost)) / (v_current_stock + v_line.quantity), 4)
    END,
    updated_at = timezone('utc'::text, now())
  WHERE id = v_line.product_id AND company_id = p_company_id;

  INSERT INTO public.stock_movements(company_id, stock_id, user_id, quantity, type, notes)
  VALUES (p_company_id, v_stock_id, p_user_id, v_line.quantity, 'supermarket_purchase_receipt', 'Purchase ' || v_order.order_number);

  v_lot_code := COALESCE(NULLIF(trim(v_line.lot_code), ''), 'OC-' || v_order.order_number::TEXT);
  INSERT INTO public.supermarket_stock_lots(
    company_id, branch_id, product_id, purchase_order_line_id, lot_code,
    quantity_received, quantity_remaining, expiration_date, received_on
  ) VALUES (
    p_company_id, p_branch_id, v_line.product_id, v_line.id, v_lot_code,
    v_line.quantity, v_line.quantity, v_line.expiration_date, CURRENT_DATE
  )
  ON CONFLICT (company_id, branch_id, product_id, lot_code) DO UPDATE SET
    quantity_received = public.supermarket_stock_lots.quantity_received + EXCLUDED.quantity_received,
    quantity_remaining = public.supermarket_stock_lots.quantity_remaining + EXCLUDED.quantity_remaining,
    expiration_date = COALESCE(EXCLUDED.expiration_date, public.supermarket_stock_lots.expiration_date);

  UPDATE public.supermarket_purchase_orders SET
    status = 'received',
    received_at = timezone('utc'::text, now()),
    updated_at = timezone('utc'::text, now())
  WHERE id = v_order.id;
  RETURN v_order.id;
END;
$$;

CREATE OR REPLACE FUNCTION public.supermarket_list_lots(p_company_id UUID, p_branch_id UUID)
RETURNS TABLE(
  id UUID, product_id UUID, lot_code TEXT, quantity NUMERIC,
  expiration_date DATE, received_date DATE
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, pg_catalog
AS $$
BEGIN
  PERFORM public.supermarket_assert_scope(p_company_id, p_branch_id);
  RETURN QUERY
  SELECT
    sl.id,
    sl.product_id,
    sl.lot_code::TEXT,
    sl.quantity_remaining,
    sl.expiration_date,
    sl.received_on
  FROM public.supermarket_stock_lots sl
  WHERE sl.company_id = p_company_id AND sl.branch_id = p_branch_id
  ORDER BY sl.expiration_date ASC NULLS LAST, sl.received_on ASC;
END;
$$;

REVOKE ALL ON FUNCTION public.supermarket_assert_scope(UUID, UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.supermarket_list_products(UUID, UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.supermarket_save_product(UUID, UUID, UUID, UUID, TEXT, TEXT, NUMERIC, NUMERIC, NUMERIC, NUMERIC, TEXT, TEXT, BOOLEAN, TEXT, TEXT, TEXT, BOOLEAN) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.supermarket_list_purchases(UUID, UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.supermarket_save_purchase(UUID, UUID, UUID, UUID, TEXT, UUID, NUMERIC, NUMERIC, DATE, TEXT, TEXT, DATE) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.supermarket_receive_purchase(UUID, UUID, UUID, UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.supermarket_list_lots(UUID, UUID) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION public.supermarket_assert_scope(UUID, UUID) TO service_role;
GRANT EXECUTE ON FUNCTION public.supermarket_list_products(UUID, UUID) TO service_role;
GRANT EXECUTE ON FUNCTION public.supermarket_save_product(UUID, UUID, UUID, UUID, TEXT, TEXT, NUMERIC, NUMERIC, NUMERIC, NUMERIC, TEXT, TEXT, BOOLEAN, TEXT, TEXT, TEXT, BOOLEAN) TO service_role;
GRANT EXECUTE ON FUNCTION public.supermarket_list_purchases(UUID, UUID) TO service_role;
GRANT EXECUTE ON FUNCTION public.supermarket_save_purchase(UUID, UUID, UUID, UUID, TEXT, UUID, NUMERIC, NUMERIC, DATE, TEXT, TEXT, DATE) TO service_role;
GRANT EXECUTE ON FUNCTION public.supermarket_receive_purchase(UUID, UUID, UUID, UUID) TO service_role;
GRANT EXECUTE ON FUNCTION public.supermarket_list_lots(UUID, UUID) TO service_role;
