-- Gastronomy cash sessions, split payments, tips and transactional table settlement.

WITH permission_definitions(name, description) AS (
  VALUES
    ('gastronomy.cash.read', 'View gastronomy cash status and settlements'),
    ('gastronomy.cash.manage', 'Open and close gastronomy cash registers'),
    ('gastronomy.settlements.read', 'View gastronomy table settlements'),
    ('gastronomy.settlements.create', 'Settle gastronomy tables and register payments')
)
INSERT INTO public.permissions(module_id, name, description)
SELECT m.id, d.name, d.description
FROM permission_definitions d
JOIN public.modules m ON m.code = 'gastronomy_tables'
ON CONFLICT (name) DO UPDATE SET description = EXCLUDED.description;

CREATE TABLE IF NOT EXISTS public.gastronomy_settlements (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID REFERENCES public.companies(id) ON DELETE CASCADE NOT NULL,
  branch_id UUID REFERENCES public.branches(id) ON DELETE RESTRICT NOT NULL,
  caja_id UUID REFERENCES public.cajas(id) ON DELETE RESTRICT NOT NULL,
  sale_id UUID REFERENCES public.sales(id) ON DELETE RESTRICT NOT NULL,
  table_id UUID REFERENCES public.gastronomy_dining_tables(id) ON DELETE RESTRICT NOT NULL,
  user_id UUID NOT NULL,
  settlement_number BIGINT GENERATED BY DEFAULT AS IDENTITY,
  idempotency_key VARCHAR(128) NOT NULL,
  split_count INTEGER DEFAULT 1 NOT NULL CHECK (split_count BETWEEN 1 AND 20),
  subtotal NUMERIC(14, 2) NOT NULL CHECK (subtotal >= 0),
  tax_amount NUMERIC(14, 2) NOT NULL CHECK (tax_amount >= 0),
  sale_total NUMERIC(14, 2) NOT NULL CHECK (sale_total > 0),
  tip_amount NUMERIC(14, 2) DEFAULT 0 NOT NULL CHECK (tip_amount >= 0),
  charged_total NUMERIC(14, 2) NOT NULL CHECK (charged_total > 0),
  fiscal_status VARCHAR(30) DEFAULT 'pending' NOT NULL
    CHECK (fiscal_status IN ('pending', 'authorized', 'rejected', 'not_required')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(company_id, idempotency_key)
);

CREATE TABLE IF NOT EXISTS public.gastronomy_settlement_payments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID REFERENCES public.companies(id) ON DELETE CASCADE NOT NULL,
  settlement_id UUID REFERENCES public.gastronomy_settlements(id) ON DELETE CASCADE NOT NULL,
  payment_number INTEGER NOT NULL CHECK (payment_number > 0),
  payment_method VARCHAR(20) NOT NULL CHECK (payment_method IN ('cash', 'card', 'qr')),
  amount NUMERIC(14, 2) NOT NULL CHECK (amount > 0),
  reference VARCHAR(100),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(settlement_id, payment_number)
);

CREATE INDEX IF NOT EXISTS idx_gastronomy_settlements_branch
  ON public.gastronomy_settlements(company_id, branch_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_gastronomy_settlements_cash
  ON public.gastronomy_settlements(company_id, caja_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_gastronomy_settlement_payments
  ON public.gastronomy_settlement_payments(company_id, settlement_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_gastronomy_one_open_cash_per_branch
  ON public.cajas(company_id, branch_id)
  WHERE status = 'open';

ALTER TABLE public.gastronomy_settlements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gastronomy_settlement_payments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Gastronomy settlements by company" ON public.gastronomy_settlements FOR ALL
  USING (company_id = public.jwt_company_id() AND public.jwt_business_type() = 'gastronomy')
  WITH CHECK (company_id = public.jwt_company_id() AND public.jwt_business_type() = 'gastronomy');
CREATE POLICY "Gastronomy settlement payments by company" ON public.gastronomy_settlement_payments FOR ALL
  USING (company_id = public.jwt_company_id() AND public.jwt_business_type() = 'gastronomy')
  WITH CHECK (company_id = public.jwt_company_id() AND public.jwt_business_type() = 'gastronomy');

CREATE OR REPLACE FUNCTION public.gastronomy_get_cash_state(p_company_id UUID, p_branch_id UUID)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_cash public.cajas%ROWTYPE;
  v_sales NUMERIC(14, 2) := 0;
  v_cash_payments NUMERIC(14, 2) := 0;
  v_card_payments NUMERIC(14, 2) := 0;
  v_qr_payments NUMERIC(14, 2) := 0;
  v_tips NUMERIC(14, 2) := 0;
BEGIN
  SELECT * INTO v_cash FROM public.cajas
  WHERE company_id = p_company_id AND branch_id = p_branch_id AND status = 'open'
  ORDER BY opened_at DESC LIMIT 1;
  IF NOT FOUND THEN
    RETURN jsonb_build_object(
      'isOpen', false, 'cashId', NULL, 'name', 'Caja Gastronomia',
      'openingBalance', 0, 'expectedCash', 0, 'salesTotal', 0,
      'cashPayments', 0, 'cardPayments', 0, 'qrPayments', 0, 'tipsTotal', 0,
      'openedAt', NULL
    );
  END IF;

  SELECT
    COALESCE(SUM(s.sale_total), 0),
    COALESCE(SUM(s.tip_amount), 0)
  INTO v_sales, v_tips
  FROM public.gastronomy_settlements s
  WHERE s.company_id = p_company_id AND s.caja_id = v_cash.id;
  SELECT
    COALESCE(SUM(CASE WHEN m.payment_method = 'cash' THEN m.amount ELSE 0 END), 0),
    COALESCE(SUM(CASE WHEN m.payment_method = 'card' THEN m.amount ELSE 0 END), 0),
    COALESCE(SUM(CASE WHEN m.payment_method = 'qr' THEN m.amount ELSE 0 END), 0)
  INTO v_cash_payments, v_card_payments, v_qr_payments
  FROM public.caja_movements m
  WHERE m.company_id = p_company_id AND m.caja_id = v_cash.id AND m.type = 'gastronomy_settlement';

  RETURN jsonb_build_object(
    'isOpen', true,
    'cashId', v_cash.id,
    'name', v_cash.name,
    'openingBalance', v_cash.opening_balance,
    'expectedCash', v_cash.opening_balance + v_cash_payments,
    'salesTotal', v_sales,
    'cashPayments', v_cash_payments,
    'cardPayments', v_card_payments,
    'qrPayments', v_qr_payments,
    'tipsTotal', v_tips,
    'openedAt', v_cash.opened_at
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.gastronomy_open_cash(
  p_company_id UUID,
  p_branch_id UUID,
  p_user_id UUID,
  p_opening_balance NUMERIC
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_catalog
AS $$
DECLARE
  v_cash_id UUID;
BEGIN
  IF p_opening_balance < 0 THEN RAISE EXCEPTION 'INVALID_OPENING_BALANCE'; END IF;
  IF NOT EXISTS (SELECT 1 FROM public.branches WHERE id = p_branch_id AND company_id = p_company_id) THEN
    RAISE EXCEPTION 'BRANCH_COMPANY_MISMATCH';
  END IF;
  IF EXISTS (
    SELECT 1 FROM public.cajas
    WHERE company_id = p_company_id AND branch_id = p_branch_id AND status = 'open'
  ) THEN RAISE EXCEPTION 'CASH_ALREADY_OPEN'; END IF;

  INSERT INTO public.cajas(
    company_id, branch_id, name, status, opened_at, opened_by, opening_balance
  ) VALUES (
    p_company_id, p_branch_id, 'Caja Gastronomia', 'open', timezone('utc'::text, now()),
    p_user_id, p_opening_balance
  ) RETURNING id INTO v_cash_id;
  RETURN v_cash_id;
EXCEPTION
  WHEN unique_violation THEN RAISE EXCEPTION 'CASH_ALREADY_OPEN';
END;
$$;

CREATE OR REPLACE FUNCTION public.gastronomy_close_cash(
  p_company_id UUID,
  p_branch_id UUID,
  p_user_id UUID,
  p_declared_cash NUMERIC
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_catalog
AS $$
DECLARE
  v_cash public.cajas%ROWTYPE;
  v_cash_payments NUMERIC(14, 2) := 0;
  v_expected NUMERIC(14, 2);
BEGIN
  IF p_declared_cash < 0 THEN RAISE EXCEPTION 'INVALID_DECLARED_CASH'; END IF;
  SELECT * INTO v_cash FROM public.cajas
  WHERE company_id = p_company_id AND branch_id = p_branch_id AND status = 'open'
  ORDER BY opened_at DESC LIMIT 1 FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'CASH_NOT_OPEN'; END IF;
  SELECT COALESCE(SUM(amount), 0) INTO v_cash_payments FROM public.caja_movements
  WHERE company_id = p_company_id AND caja_id = v_cash.id
    AND type = 'gastronomy_settlement' AND payment_method = 'cash';
  v_expected := v_cash.opening_balance + v_cash_payments;
  UPDATE public.cajas SET
    status = 'closed',
    closed_at = timezone('utc'::text, now()),
    closed_by = p_user_id,
    closing_balance = p_declared_cash
  WHERE id = v_cash.id;
  RETURN jsonb_build_object(
    'cashId', v_cash.id,
    'expectedCash', v_expected,
    'declaredCash', p_declared_cash,
    'difference', ROUND(p_declared_cash - v_expected, 2)
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.gastronomy_list_settlements(p_company_id UUID, p_branch_id UUID)
RETURNS TABLE(
  id UUID, settlement_number BIGINT, table_name TEXT, sale_id UUID,
  sale_total NUMERIC, tip_amount NUMERIC, charged_total NUMERIC,
  split_count INTEGER, fiscal_status TEXT, payments JSONB,
  created_at TIMESTAMP WITH TIME ZONE
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT s.id, s.settlement_number, t.name::TEXT, s.sale_id, s.sale_total,
    s.tip_amount, s.charged_total, s.split_count, s.fiscal_status::TEXT,
    COALESCE(jsonb_agg(jsonb_build_object(
      'paymentNumber', p.payment_number,
      'method', p.payment_method,
      'amount', p.amount,
      'reference', COALESCE(p.reference, '')
    ) ORDER BY p.payment_number) FILTER (WHERE p.id IS NOT NULL), '[]'::jsonb),
    s.created_at
  FROM public.gastronomy_settlements s
  JOIN public.gastronomy_dining_tables t ON t.id = s.table_id AND t.company_id = s.company_id
  LEFT JOIN public.gastronomy_settlement_payments p
    ON p.settlement_id = s.id AND p.company_id = s.company_id
  WHERE s.company_id = p_company_id AND s.branch_id = p_branch_id
  GROUP BY s.id, t.name
  ORDER BY s.created_at DESC
  LIMIT 100;
$$;

CREATE OR REPLACE FUNCTION public.gastronomy_settle_table(
  p_company_id UUID,
  p_branch_id UUID,
  p_user_id UUID,
  p_table_id UUID,
  p_idempotency_key TEXT,
  p_split_count INTEGER,
  p_tip_amount NUMERIC,
  p_payments JSONB
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_catalog
AS $$
DECLARE
  v_existing public.gastronomy_settlements%ROWTYPE;
  v_cash public.cajas%ROWTYPE;
  v_table public.gastronomy_dining_tables%ROWTYPE;
  v_sale_id UUID;
  v_settlement_id UUID;
  v_settlement_number BIGINT;
  v_sale_total NUMERIC(14, 2);
  v_subtotal NUMERIC(14, 2);
  v_tax NUMERIC(14, 2);
  v_charged_total NUMERIC(14, 2);
  v_payment_total NUMERIC(14, 2);
  v_payment_method TEXT;
  v_payment RECORD;
BEGIN
  IF p_idempotency_key IS NULL OR length(p_idempotency_key) < 8 OR length(p_idempotency_key) > 128 THEN
    RAISE EXCEPTION 'INVALID_IDEMPOTENCY_KEY';
  END IF;
  IF p_split_count < 1 OR p_split_count > 20 OR p_tip_amount < 0
    OR jsonb_typeof(p_payments) <> 'array' OR jsonb_array_length(p_payments) <> p_split_count THEN
    RAISE EXCEPTION 'INVALID_SETTLEMENT';
  END IF;
  SELECT * INTO v_existing FROM public.gastronomy_settlements
  WHERE company_id = p_company_id AND idempotency_key = p_idempotency_key;
  IF FOUND THEN
    RETURN jsonb_build_object(
      'settlementId', v_existing.id, 'settlementNumber', v_existing.settlement_number,
      'saleId', v_existing.sale_id, 'saleTotal', v_existing.sale_total,
      'tipAmount', v_existing.tip_amount, 'chargedTotal', v_existing.charged_total,
      'fiscalStatus', v_existing.fiscal_status, 'duplicate', true
    );
  END IF;

  SELECT * INTO v_cash FROM public.cajas
  WHERE company_id = p_company_id AND branch_id = p_branch_id AND status = 'open'
  ORDER BY opened_at DESC LIMIT 1 FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'CASH_NOT_OPEN'; END IF;
  SELECT * INTO v_table FROM public.gastronomy_dining_tables
  WHERE id = p_table_id AND company_id = p_company_id AND branch_id = p_branch_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'TABLE_NOT_FOUND'; END IF;

  -- Recheck idempotency after taking operational locks for concurrent retries.
  SELECT * INTO v_existing FROM public.gastronomy_settlements
  WHERE company_id = p_company_id AND idempotency_key = p_idempotency_key;
  IF FOUND THEN
    RETURN jsonb_build_object(
      'settlementId', v_existing.id, 'settlementNumber', v_existing.settlement_number,
      'saleId', v_existing.sale_id, 'saleTotal', v_existing.sale_total,
      'tipAmount', v_existing.tip_amount, 'chargedTotal', v_existing.charged_total,
      'fiscalStatus', v_existing.fiscal_status, 'duplicate', true
    );
  END IF;

  PERFORM 1 FROM public.gastronomy_orders o
  WHERE o.company_id = p_company_id AND o.branch_id = p_branch_id
    AND o.table_id = p_table_id AND o.status NOT IN ('closed', 'cancelled')
  FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'TABLE_HAS_NO_OPEN_ORDERS'; END IF;

  SELECT
    ROUND(SUM(oi.quantity * oi.unit_price), 2),
    ROUND(SUM((oi.quantity * oi.unit_price) / (1 + p.vat_rate / 100)), 2)
  INTO v_sale_total, v_subtotal
  FROM public.gastronomy_orders o
  JOIN public.gastronomy_order_items oi
    ON oi.order_id = o.id AND oi.company_id = o.company_id AND oi.status <> 'cancelled'
  JOIN public.products p ON p.id = oi.product_id AND p.company_id = o.company_id
  WHERE o.company_id = p_company_id AND o.branch_id = p_branch_id
    AND o.table_id = p_table_id AND o.status NOT IN ('closed', 'cancelled');
  IF COALESCE(v_sale_total, 0) <= 0 THEN RAISE EXCEPTION 'EMPTY_SETTLEMENT'; END IF;
  v_tax := ROUND(v_sale_total - v_subtotal, 2);
  v_charged_total := ROUND(v_sale_total + p_tip_amount, 2);

  IF EXISTS (
    SELECT 1 FROM jsonb_array_elements(p_payments) payment
    WHERE payment->>'method' NOT IN ('cash', 'card', 'qr')
      OR COALESCE((payment->>'amount')::NUMERIC, 0) <= 0
  ) THEN RAISE EXCEPTION 'INVALID_SETTLEMENT_PAYMENT'; END IF;
  SELECT ROUND(SUM((payment->>'amount')::NUMERIC), 2) INTO v_payment_total
  FROM jsonb_array_elements(p_payments) payment;
  IF ABS(v_payment_total - v_charged_total) > 0.01 THEN RAISE EXCEPTION 'SETTLEMENT_TOTAL_MISMATCH'; END IF;
  SELECT CASE WHEN COUNT(DISTINCT payment->>'method') = 1 THEN MIN(payment->>'method') ELSE 'mixed' END
  INTO v_payment_method FROM jsonb_array_elements(p_payments) payment;

  INSERT INTO public.sales(
    company_id, branch_id, caja_id, user_id, subtotal, discount, tax_amount,
    total, payment_method, status
  ) VALUES (
    p_company_id, p_branch_id, v_cash.id, p_user_id, v_subtotal, 0, v_tax,
    v_sale_total, v_payment_method, 'completed'
  ) RETURNING id INTO v_sale_id;

  INSERT INTO public.sale_items(
    company_id, sale_id, product_id, quantity, unit_price, discount, tax_rate, subtotal
  )
  SELECT p_company_id, v_sale_id, oi.product_id, SUM(oi.quantity), MAX(oi.unit_price), 0,
    MAX(p.vat_rate), ROUND(SUM(oi.quantity * oi.unit_price), 2)
  FROM public.gastronomy_orders o
  JOIN public.gastronomy_order_items oi
    ON oi.order_id = o.id AND oi.company_id = o.company_id AND oi.status <> 'cancelled'
  JOIN public.products p ON p.id = oi.product_id AND p.company_id = o.company_id
  WHERE o.company_id = p_company_id AND o.branch_id = p_branch_id
    AND o.table_id = p_table_id AND o.status NOT IN ('closed', 'cancelled')
  GROUP BY oi.product_id;

  INSERT INTO public.gastronomy_settlements(
    company_id, branch_id, caja_id, sale_id, table_id, user_id, idempotency_key,
    split_count, subtotal, tax_amount, sale_total, tip_amount, charged_total
  ) VALUES (
    p_company_id, p_branch_id, v_cash.id, v_sale_id, p_table_id, p_user_id,
    p_idempotency_key, p_split_count, v_subtotal, v_tax, v_sale_total,
    p_tip_amount, v_charged_total
  ) RETURNING id, settlement_number INTO v_settlement_id, v_settlement_number;

  FOR v_payment IN
    SELECT row_number() OVER ()::INTEGER AS payment_number,
      payment->>'method' AS method,
      (payment->>'amount')::NUMERIC AS amount,
      NULLIF(payment->>'reference', '') AS reference
    FROM jsonb_array_elements(p_payments) payment
  LOOP
    INSERT INTO public.gastronomy_settlement_payments(
      company_id, settlement_id, payment_number, payment_method, amount, reference
    ) VALUES (
      p_company_id, v_settlement_id, v_payment.payment_number,
      v_payment.method, v_payment.amount, v_payment.reference
    );
    INSERT INTO public.caja_movements(
      company_id, caja_id, amount, type, payment_method, reference_id, notes
    ) VALUES (
      p_company_id, v_cash.id, v_payment.amount, 'gastronomy_settlement',
      v_payment.method, v_sale_id,
      'Settlement #' || v_settlement_number || ' - ' || v_table.name
    );
  END LOOP;

  UPDATE public.gastronomy_order_items SET status = 'served'
  WHERE company_id = p_company_id AND order_id IN (
    SELECT id FROM public.gastronomy_orders
    WHERE company_id = p_company_id AND branch_id = p_branch_id
      AND table_id = p_table_id AND status NOT IN ('closed', 'cancelled')
  ) AND status <> 'cancelled';
  UPDATE public.gastronomy_orders SET status = 'closed', closed_at = timezone('utc'::text, now())
  WHERE company_id = p_company_id AND branch_id = p_branch_id
    AND table_id = p_table_id AND status NOT IN ('closed', 'cancelled');
  UPDATE public.gastronomy_dining_tables SET status = 'available'
  WHERE id = p_table_id AND company_id = p_company_id AND branch_id = p_branch_id;

  RETURN jsonb_build_object(
    'settlementId', v_settlement_id,
    'settlementNumber', v_settlement_number,
    'saleId', v_sale_id,
    'saleTotal', v_sale_total,
    'tipAmount', p_tip_amount,
    'chargedTotal', v_charged_total,
    'fiscalStatus', 'pending',
    'duplicate', false
  );
END;
$$;

REVOKE ALL ON FUNCTION public.gastronomy_get_cash_state(UUID, UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.gastronomy_open_cash(UUID, UUID, UUID, NUMERIC) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.gastronomy_close_cash(UUID, UUID, UUID, NUMERIC) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.gastronomy_list_settlements(UUID, UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.gastronomy_settle_table(UUID, UUID, UUID, UUID, TEXT, INTEGER, NUMERIC, JSONB) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.gastronomy_get_cash_state(UUID, UUID) TO service_role;
GRANT EXECUTE ON FUNCTION public.gastronomy_open_cash(UUID, UUID, UUID, NUMERIC) TO service_role;
GRANT EXECUTE ON FUNCTION public.gastronomy_close_cash(UUID, UUID, UUID, NUMERIC) TO service_role;
GRANT EXECUTE ON FUNCTION public.gastronomy_list_settlements(UUID, UUID) TO service_role;
GRANT EXECUTE ON FUNCTION public.gastronomy_settle_table(UUID, UUID, UUID, UUID, TEXT, INTEGER, NUMERIC, JSONB) TO service_role;
